### ISSUE TITLE
App building but not running.

### ISSUE THREAD

**Issue by vyasgiridhar** [pockethub/PocketHub#1000]
Pocket hub is stopping each time i open it.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.pockethub/com.github.pockethub.ui.MainActivity}: java.lang.SecurityException: uid 10104 cannot get user data for accounts of type: com.github
```
```
java.io.FileNotFoundException: com/google/inject/internal/util/$Finalizer.class
```

**Comment by vyasgiridhar** [comment]
```Caused by: java.lang.SecurityException: uid 10106 cannot get user data for accounts of type: com.github
```

**Comment by Meisolsson** [comment]
Any more info?

1. What Android version are you running?
2. Do you know of any apps on your device which connect to Github apart from this one?
3. A line number would be nice (if there is one)

**Comment by vyasgiridhar** [comment]
Sorry Could not reply early as i had some work.

This app doesn't seem to work in CM 13  based rom. 
it works fine in the emulator.

**Comment by vyasgiridhar** [comment]
I uninstalled another github app and pocket hub works fine
What is this causing an error?

**Comment by hzsweers** [comment]
Probably one of the many forks that didn't actually change account manager credentials? Closing for now then.
