### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by robtec** [pockethub/PocketHub#1007]
Question, new user to the app, is there notifications?

Cheers

**Comment by cmacdonnacha** [comment]
+1

**Comment by cmacdonnacha** [comment]
+1

**Comment by knucklehed** [comment]
777

**Comment by Meisolsson** [comment]
There are not. The next release (0.2.0) will have the notification center but not push notifications.

**Comment by robtec** [comment]
Cool, thanks
