### ISSUE TITLE
Can't install PocketHub from Play Store on Android Nougat (final)

### ISSUE THREAD

**Issue by StefMa** [pockethub/PocketHub#1012]
I've noticed that PocketHub is finally in the playstore.
I had removed my previous dev version from PocketHub and want to install the Store Version.

The Store download and want to install. After a little "install time" i got a error code -505 from play store...

**Comment by StefMa** [comment]
@Meisolsson

**Comment by StefMa** [comment]
I've checked the log and found that
```
com.android.server.pm.PackageManagerException: Can't install because provider name com.github.sync (in package com.github.pockethub.android) is already used by com.github.pockethub
```

**Comment by hzsweers** [comment]
Strange, worked fine for me

**Comment by hzsweers** [comment]
Strange, worked fine for me

**Comment by Meisolsson** [comment]
There could be a problem with the account still being on the device. Check Settings->Accounts and see if the pockethub account is there.

**Comment by StefMa** [comment]
Sry, i'm dump -.-
Have only removed old PocketHub from desctop. But not fully :/
Now it's worked... Sry for the trouble
