### ISSUE TITLE
Rename authorized application?

### ISSUE THREAD

**Issue by hidroh** [pockethub/PocketHub#1014]
Hey, congrats on the release of PocketHub to Play Store! I just tried it out and it looks real smooth. 

There is just 1 small issue I noticed when going thru the authorization flow for the 1st time: The authorized application is called 'GitHubTest', instead of 'PocketHub'.

Also the website listed for 'GitHubTest' seems to be not related nor accessible http://hemserver.dmz.se/, probably we can change it to https://github.com/pockethub/PocketHub, or maybe even better to [GitHub pages](https://github.com/blog/2228-simpler-github-pages-publishing)?

**Comment by Meisolsson** [comment]
Thanks for pointing that out. Both of these things will be fixed in the next release.

**Comment by Meisolsson** [comment]
This has been done
