### ISSUE TITLE
Setup Environment Stack...

### ISSUE THREAD

**Issue by elsot2** [pockethub/PocketHub#1017]
Hi, im new android developer, i have some diffuculties with the set up of application. Is there simplest instruction to set up?

**Comment by larsgrefer** [comment]
Just open the project with Android Studio and follow these steps: https://github.com/pockethub/PocketHub#setup-environment

**Comment by srbhmshr344** [comment]
can you please tell me where are you actually facing difficulty ? :) @elsot2

**Comment by elsot2** [comment]
At first option i need to create a new OAuth Application, for that i need an Application name, which i use PocketHub.. But for the Homepage URL and CallbackURL i dont know em, and they are for web app i think..

**Comment by lakeoffaith** [comment]
can anyone show me what how to write Homepage URL ,thanks,
i git it http://127.0.0.1
i get the Client ID and Client Secret,do it as the readme .
i set the callbackurl https://hao123.com.

i start run the app in android studio ,when i click login it show me
java.lang.IllegalStateException: Missing required properties: code

can anybody give me some tips.
