### ISSUE TITLE
survey data missing!  

### ISSUE THREAD

**Issue by returnight** [pockethub/PocketHub#1018]
09-07 11:13:39.284 1775-1775/? D/StatusBar.NetworkController: onSignalStrengthsChanged received on slotId :0signalStrength=SignalStrength: 13 99 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 gsm|lte level=5 cdmdlevel=0 evdolevel=0
09-07 11:13:41.898 2289-26847/? D/SecurityCenter: memDiff : 2, timeDiff : 1473218021899
09-07 11:13:41.968 1832-1832/? D/wpa_supplicant: RX ctrl_iface - hexdump(len=11): 53 49 47 4e 41 4c 5f 50 4f 4c 4c
09-07 11:13:41.968 1832-1832/? D/wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
09-07 11:13:41.977 1832-1832/? D/wpa_supplicant: nl80211: survey data missing!

**Comment by hzsweers** [comment]
Unrelated
