### ISSUE TITLE
Two factor authentication issue

### ISSUE THREAD

**Issue by antonkallenberg** [pockethub/PocketHub#1019]
Can't sign in using two factor authentication. After entering the auth code from the sms I am redirected back to the "enter username/password"-view with a message telling me that my username and/or password is wrong.

**Comment by Meisolsson** [comment]
I just tested this an had no problem, I'll try it with another version later. For now I guess you could try again.

Are you using 2-fa via SMS or something else? (Not sure if it would make a difference)

**Comment by antonkallenberg** [comment]
I was using the prior version of this app, after updating the authentication works as expected, thanks!

**Comment by niskajace8** [comment]
![image](https://cloud.githubusercontent.com/assets/21243759/18822276/9a2f5f3e-8373-11e6-8137-7a97e3a55473.png)

**Comment by niskajace8** [comment]
Can sum one help me please
