### ISSUE TITLE
Can't install PocketHub from Play Store on Samsung Galaxy S6

### ISSUE THREAD

**Issue by Akronix** [pockethub/PocketHub#1023]
Hi!

I'm unable to install PocketHub on my Samsung Galaxy S6 running Android 6.0.1.
The download completes successfully but then an error message saying the following appears:

> **Can't install app**
> "PocketHub for Github" can't be installed. Try again, and if the problem continues, get help troubleshooting (Error code: -505)

**Comment by Juwdohr** [comment]
Have you tried recently? I was able to download on my Samsung Galaxy Note5 that is running Android 6.01. But it seems to keep crashing when I try to use the app after authorizing.

**Comment by Akronix** [comment]
Just tried now. Same result :confused:

**Comment by Juwdohr** [comment]
Guess the bug is in the news feed, and because of the SDK they are currently using. A @Meisolsson said there would be a fix soon.

**Comment by Meisolsson** [comment]
No clue if the new update will fix this issue. If not you can reopen this.

**Comment by Akronix** [comment]
Tried two days ago and tried again this morning. No luck, It still doesn't work.

**Comment by hzsweers** [comment]
That issue seems like a play store bug, not sure there's anything we can do
