### ISSUE TITLE
Galaxy Note 5 issues

### ISSUE THREAD

**Issue by Juwdohr** [pockethub/PocketHub#1026]
I have a Galaxy Note 5, running Android V6.0.1. I just found out about this app. I downloaded it, and was able to authorize it just fine. But now every time I open the application, it seems to crash. I have sent in a report about this via the report function on my phone. Not sure if anyone else is having issues.

**Comment by Meisolsson** [comment]
The bug is in the news feed and because of the SDK we currently use. There will be fix soon.

**Comment by Meisolsson** [comment]
Should be fixed in the newest version.

**Comment by Juwdohr** [comment]
When is the newest version supposed to be released?



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by Meisolsson** [comment]
Should be on phones in a couple of hours, guessing latest tomorrow.
