### ISSUE TITLE
Can't Open Code

### ISSUE THREAD

**Issue by Juwdohr** [pockethub/PocketHub#1031]
I am having issues with opening up the code files or even a issue on PocketHub. I am currently running on a Samsung Galaxy Note 5, with Android 6.0.1 (getting "Loading file failed" error).

If you need any more information please contact me.

**Comment by Meisolsson** [comment]
The bug is fixed in master, the update will be pushed soon.

**Comment by Juwdohr** [comment]
How often are the updates pushed?

**Comment by Meisolsson** [comment]
For the moment when I have the time and haven't found any major bugs.
