### ISSUE TITLE
Direct download for the APK file

### ISSUE THREAD

**Issue by fanthos** [pockethub/PocketHub#1035]
I had a dig in this repo and Google, and did not find a reliable way to download the APK file without Google play store. Is there any official way I can download the APK file directly?

Google play store on my device stop working for unknown reason.

**Comment by Meisolsson** [comment]
For now the answer is no. It will only be uploaded to Google Play. This might change in the future.

**Comment by IzzySoft** [comment]
A real pity the APK of an open-source project can only be accessed via a closed-source market. Why not publish releases here at Github again (the last time that has been done was 2/2014?) and attach the `.apk` to them? Apart from @fanthos having Playstore out-of-order, there are many others who cannot or do not want to use Playstore. May I suggest re-opening this issue and considering the solution?
