### ISSUE TITLE
Remove sharing when repositor private.

### ISSUE THREAD

**Issue by ThomasAunvik** [pockethub/PocketHub#1041]
Whats the meaning to share a private repositories?

**Comment by KOGLinese** [comment]
sorry ，i am not clear.

**Comment by ThomasAunvik** [comment]
When you go to your private repositories in the app and you can share it. I dont Thinking it is needed to have one beacuse noone can access it but the one who made it

**Comment by StefMa** [comment]
You can invite some other colleagues or whatever to this Repo and share it.
Makes totally sense to me..

**Comment by Meisolsson** [comment]
I agree with @StefMa here, closing this
