### ISSUE TITLE
Issues are completely empty

### ISSUE THREAD

**Issue by hasufell** [pockethub/PocketHub#1042]
Nothing shows up, just blank space.

Phone: Samsung Galaxy S7
github app version: 1.9.0

**Comment by salman-bhai** [comment]
Did this Issue get solved?

**Comment by hasufell** [comment]
No, this project seems abandoned. Use https://github.com/jonan/ForkHub instead.

**Comment by hzsweers** [comment]
If it were solved, it would be closed.

This issue has nothing actionable in it. Repro cases, screenshots, etc are all must haves. Henrik has been working on this project but is just one person with limited time. Nonspecific issues like this aren't very constructive.

**Comment by hzsweers** [comment]
Can revisit reopening if you can provide information mentioned above

**Comment by hasufell** [comment]
> Repro cases

Try to open an issue on an arbitrary repository.

> screenshots

Uhm, they help how? As I said, it's just blank space.

> Nonspecific issues like this aren't very constructive.

It was very specific (issue/reproduction, app version and phone type). Your app just doesn't give any more information that would be useful here. Don't blame me for that.

**Comment by hzsweers** [comment]
Just tried opening an arbitrary repository, worked fine for me.

**Comment by hasufell** [comment]
> Just tried opening an arbitrary repository, worked fine for me.

An issue on an arbitrary repository.
