### ISSUE TITLE
Upgrade to RxJava 2

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1046]
Is there any intention to upgrade to RxJava 2? Looking at the dependencies, there are 3 libraries which use Rx: RxLifecycle, RxAndroid, and GithubSdk. RxLifecycle and RxAndroid have RxJava 2 versions, but GithubSdk doesn't. However, @Meisolsson is the maintainer of the library and appears to be part of the core team working on this project. I'm not sure whether such an issue should be brought up on the GithubSdk page as well so if it should please say.

I'm interested on working on such a change, but as noted in the contributing guidelines, I'm bringing up an issue to ensure that my efforts are not wasted.

**Comment by Meisolsson** [comment]
As of recent I've not had enough time to work on this to even consider the change. It does sound interesting, if you have the time i'd be happy to have the contribution.
