### ISSUE TITLE
Use Checkstyle for Travis-CI

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1050]
To enforce a coding standard across the code base, could we use Checkstyle? My suggestion would to use Google's coding standard as it is one of the more popular ones (with the slight modification that we double the indentations i.e. from 2 to 4).

I'd be happy to work on this but just want some confirmation that such a change is desired. I've made such a change to a couple of other OSS ([here](https://github.com/commons-app/apps-android-commons/pull/361) and [here](https://github.com/davidalbers/whitenoise/pull/16)) so my contribution will be pretty similar to those.

**Comment by Meisolsson** [comment]
Looks alright, feel free to open a PR.
