### ISSUE TITLE
Use Retrolambda

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1055]
As this project is using Rx, to reduce the verbosity of the code I propose to use Retrolambda to backport lambda expressions.

**Comment by Meisolsson** [comment]
I've had this thought too so if you want to do this in combination with #1046 feel free to do so. If not I'd say we hold off on it for a while.

**Comment by veyndan** [comment]
Lambda expressions can be used for things that aren't just related to RxJava though, for example `OnClickListener`. My proposal would be that once I have completed #1046, then I could make a separate PR relating to Retrolambda.

**Comment by Meisolsson** [comment]
I do know we can use it for more then just RxJava but I still think I rather get #1046 in first. After that we can do the rest.
