### ISSUE TITLE
Setup Environment Stack

### ISSUE THREAD

**Issue by lakeoffaith** [pockethub/PocketHub#1060]
when i make the app run in androidstudio ,i get into some trouble.
can anyone show me what how to write Homepage URL ,thanks,
i git it http://127.0.0.1
i get the Client ID and Client Secret,do it as the readme .
i set the callbackurl https://hao123.com.

i start run the app in android studio ,when i click login it show me
java.lang.IllegalStateException: Missing required properties: code

can anybody give me some tips.

**Comment by Meisolsson** [comment]
The homepage URL doesn't matter. Your callback url is not going to work though. We explicitly say NOT to use https or http [here](https://github.com/pockethub/PocketHub#callback-url)
