### ISSUE TITLE
Extend from BaseAdapter instead of TypeAdapter

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1066]
I've been looking at converting all the `ListView`s to `RecyclerView`s (as per #829) but it appears that the `ListView` adapters are extending from `TypeAdapter` instead of extending directly from `BaseAdapter`.

Even though the code is generally slightly shorter than extending from `BaseAdapter` I feel that the readability of the adapters suffer significantly. A simple example of this is in [`CommitListAdapter`](https://github.com/pockethub/PocketHub/blob/master/app/src/main/java/com/github/pockethub/android/ui/commit/CommitListAdapter.java) where in the method `update(…)` we are setting the views texts or image by index which isn't very readable as we have to keep referencing what the view at such index is. Also there is no type safety here as assuming, for example, that index 2 was a `TextView` when it actually is an `ImageView` would throw a runtime exception instead of the compile time exception that extending directly from `BaseAdapter` would give.

I understand that this doesn't give much progression on using a `RecyclerView` instead of a `ListView`, but when converting a couple of them it was obvious that extending from `BaseAdapter` instead of `TypeAdapter` made the conversion much simpler as things like ViewHolder's are already in place and would only need marginal modification.

You should not only see such a change as a stepping stone to using `RecyclerView` but also as an overall improvement to the readability and maintainability of the adapter code while the migration is underway.

**Comment by Meisolsson** [comment]
I don't really think the change is necessary, I works and the only time it should throw a runtime exception in when developing.

Secondly this is a task I've already has some thoughts about. I'll create a separate issue on the migration to RecyclerView but for now I think we should leave adapters as they are.
