### ISSUE TITLE
Move to RecyclerView

### ISSUE THREAD

**Issue by Meisolsson** [pockethub/PocketHub#1067]
For the moment there's nothing wrong with the ListView's in the app but it would be nice and open up some new opportunities if we switched to RecyclerView.

Though there are some things to bear in mind:
1. Headers and footers are required. (Sticky headers are a plus)
2. Needs to handle multiple view types in the same list.
(If there's more, do tell me)

I've had a look at [Groupie](https://github.com/lisawray/groupie) and I like the way you can easily build the lists. This is what I'd prefer we implement.

**Comment by veyndan** [comment]
I've been using [AdapterDelegates](https://github.com/sockeqwe/AdapterDelegates) in my own app for a while and it has been a delight to use, plus it is very lightweight (only 6 classes). I haven't used Groupie before but from a quick glance at the README, it seems like AdapterDelegates is less invasive as you don't have to extend your models with any classes.

**Comment by Meisolsson** [comment]
You don't have to extend your models with anything. You do have to create a class binding the data to the view (Since it uses view binding) but that also means less `textView.setText(...)` in the code. I gonna be looking both at AdapterDelegates more but also waiting too see what happens to Groupie since it's a young project. Someone is implementing Sticky headers on top of it so that would be kind of nice to have.

**Comment by veyndan** [comment]
Sorry I must have misunderstood the README on the first pass.

As Groupie uses data binding (and it appears that you aren't suggesting to just use the generated view binder of data binding without the other aspects of data binding), does this mean that the architecture of PocketHub is migrating towards MVVM?

From the looks of it, Groupie seems to have a lot of features whereas AdapterDelegates is more bare bones, so I guess it depends on your slant. Do you have any more information about the implementation of the sticky headers e.g. will it be a fork of Groupie or will it be part of the library? Is there currently a GitHub issue for it if so?

**Comment by Meisolsson** [comment]
The guy has only made a PR for a small change to allow him to add it but it's implemented in his fork. [here](https://github.com/restor1/groupie), and the diff is [here](https://github.com/lisawray/groupie/compare/master...restor1:master)

**Comment by veyndan** [comment]
Looks good, do you think it is best to wait for the PR to be merged before implementing the RecyclerView in case there is any changes to the Groupie API if it is merged?

**Comment by Meisolsson** [comment]
We'll I'm still thinking about which I prefer, AdapterDelegates or Groupie. Will take a day or two to decide completely.

**Comment by Meisolsson** [comment]
Gonna go for AdapterDelegates for three reasons.
1. It's more mature than Groupie and will probably give us less problems when implementing.
2. When I last checked we were very close to the 64k DEX limit and databinding/Groupie would probably push us over that.
3. There will be less code to refactor since we don't have to move everything to XML.

There are somthing that we should remember doing when we migrate to RecyclerView:
* Headers and footers are important for now. We can simply extend the adapter from AdapterDelegates and att some logic above it to handle headers and footers.
* Try to split up `IconAndViewTextManager` into multiple adapters (Feels like a huge class to have)

**Comment by veyndan** [comment]
> Headers and footers are important for now. We can simply extend the adapter from AdapterDelegates and att some logic above it to handle headers and footers.

Couldn't we just have two separate AdapterDelegates, one which is a header and one which is a footer? Or is that what you meant by the above?

**Comment by Meisolsson** [comment]
Well we could but that still means we need to pass a list with the headers/footers inside it. What it mean is that the actual adapter should handle the headers and footers. Like this.

1. We set a list of comments on the adapter
2. We call addHeader on the adapter.
3. The adapter itself ads the header above all other items.
4. When replacing/updating the comments the header is the same.

This way the activity/fragment doesn't need to handle any header work. Unless the headers are inside the list as:

**Header
Notification
Notification
Header
Notification
Notification
Header**

**Comment by veyndan** [comment]
Is fast scroll on the list view still a desired feature? RecyclerView doesn't natively support this and a third party library would have to be pulled in (or implement ourselves). Personally, I think the fast scroller should just be removed as I can't see a use case where you would want to scroll to random parts of the list at a moments notice. This also eases migration to using a RecyclerView.
