### ISSUE TITLE
Stop use of ViewUtils.setGone(…)

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1073]
`ViewUtils.setGone(…)` contains a [boolean trap](https://ariya.io/2011/08/hall-of-api-shame-boolean-trap) making the code confusing to read sometimes. Personally the confusion arises with the boolean parameter as it is unclear whether setting it to `false` arises in a) keep the same visibility or b) do the opposite of `ViewUtils.setGone(…)` i.e. set the visibility to `View.VISIBLE`. Obviously by reading the JavaDoc it says that the second case is correct but containing the intent of the method via a JavaDoc is a regression to the normal way of setting the visibility via `View#setVisibility(View.X)`.

I'd advocate reverting back to using `View#setVisibility(View.X)` as it is clear what the line of code is doing without having to succumb to reading documentation. I feel that the slight increase in verbosity through this change will be greatly outweighed by the improvement in the readability of the code.

**Comment by Meisolsson** [comment]
Good idea, there is a plan (as always just in my head) to remove [Wishlist](https://github.com/kevinsawicki/wishlist) since it's ancient and and we needed a custom build. The problem is mostly that the app is practically built on top of it so theres lots to change.

**Comment by veyndan** [comment]
I've been having similar thoughts. Once we replace all instances of `ListView` with `RecyclerView` as per #1067, removing Wishlist should be fairly trivial as the `ListView` adapters from Wishlist has plagued the code.
