### ISSUE TITLE
App Crashes While Loading the README of Repository

### ISSUE THREAD

**Issue by RamolaWeb** [pockethub/PocketHub#1084]
![screenshot from 2017-04-05 20-31-31](https://cloud.githubusercontent.com/assets/12547818/24712590/d84d17b6-1a40-11e7-97a3-824a3e4cc4bd.png)
The App get Crashed when loading the **README** and then swiping to the **NEWS** section of the Repository . Then the Toast Prompt displaying Loading Code Failed. The Log of the android monitor states that the thread is being interrupted while loading the **README** section.

**Comment by veyndan** [comment]
Is the projects README that this crashed on open to the public, and if so can you link the project?

**Comment by RamolaWeb** [comment]
@veyndan  The app is crashing while README is loading and we swipe to the next tab and when we came back to the README Section it get Crashes. This Happen also with the other tabs which are still loading and when we swipe to other tabs and again came back to it , the app crashes.

**Comment by veyndan** [comment]
I see, thanks. I'll have a look into why this happens

**Comment by salman-bhai** [comment]
Any headway on this Issue?

**Comment by veyndan** [comment]
Unfortunately I've stopped working on this project due to the slow PR approval process and fairly inactive community making progress on this project sluggish. If anyone else would like to take on this issue, please do so.

**Comment by Meisolsson** [comment]
This should be fixed by #1106.
