### ISSUE TITLE
Authorize button is disabled during first login

### ISSUE THREAD

**Issue by SparK-Cruz** [pockethub/PocketHub#1104]
![screenshot_20170531-115828](https://cloud.githubusercontent.com/assets/1179000/26638483/9b81d586-45f8-11e7-9cf2-20b578290bf2.png)

Can't login because Authorize button is disabled, not sure why.
I have 2FA enabled and all but I don't think it's related. (And I won't disable it to test)

**Comment by LousyLynx** [comment]
I am getting the same issue

**Comment by Meisolsson** [comment]
I will look into this later this week. If I haven't responded before Saturday just ping me.

**Comment by Meisolsson** [comment]
The problem occurs since GitHub now uses javascript to activate the button. And Android's WebView disables javascript by default. There will be a fix pushed once I get time.
