### ISSUE TITLE
Can't authorize app: browser not supported

### ISSUE THREAD

**Issue by ppazos** [pockethub/PocketHub#1112]
Got this screen when trying to login, strange it has an IE icon. I have last version of chrome in my device. What is happening?

![2017-06-17-21-54-24](https://user-images.githubusercontent.com/1278556/27257319-2d9aa74c-53a8-11e7-82d7-cfb7b9f384de.png)

**Comment by Meisolsson** [comment]
Guessing this is because we use WebView and all devices don't have a updated WebView which might lead to this behaviour.

Can you login in your normal browser?

**Comment by ppazos** [comment]
I can login perfectly from the web on the phone using chrome.

**Comment by Meisolsson** [comment]
Alright, then I'll try to fix this in the coming days.
