### ISSUE TITLE
Remove welcome screen

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1116]
The only information the welcome screen has is of a brief history of how the app came to be. I don't feel that this is necessary for the users to know. This information may be interesting to developers of the app, and hence this information already being in the README seems like enough.

There are two main benefits to removing the welcome screen (which I can think of):

- Allows the user to skip (imo) irrelevant information and allow them to login straight away.
- Removes all maintenance overhead that this component of the app entails (e.g. bugs, translations)

**Comment by Meisolsson** [comment]
Well the feature is implemented and there should be no huge overhead of bugs to fix there. There is a skip button so if the user dosen't care they can skip early. 

So it will stay.

**Comment by veyndan** [comment]
I feel this feature is making the experience worse, even if there is a skip button. So the suggestion is to really just remove a bad feature. I guess this is just personal preference but generally when there is an intro screen like that, it gives a quick tutorial/overview of what the app does, not a history of how the app came to be.

**Comment by Meisolsson** [comment]
Yeah, sorry about that. I've had a rough week at work and should not have even commented earlier.

I do see the maintenance work for translations but that's not my biggest concern around the project right now.

For the user side I think we did it to push the old users over. So this might have served it's purpose.

So as is see it for now I'd rather work on fixing up the thing that actually are broken than things that work and aren't hurting the app (which I don't think this is). But if you really feel that it's hurting the app then remove it or incorporate it better with the login flow maybe.

Once again sorry for just closing it like that, will try to keep those to a minimum.

**Comment by veyndan** [comment]
That's alright, we all have those sort of weeks.

I agree that it is better to fix actual bugs, but sometimes removing code bloat makes it easier to figure out where the problems are.

I'm not sure whether it is better to just remove the information or incorporate in the login flow as you said. I'll take some time to mull it over or if you have any preference I'd be interested in hearing it.
