### ISSUE TITLE
News redesign

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1120]
I am proposing that we make the bolded text (the circled elements in the mobile screenshot) clickable, aligning with what is found on the website.

There are a few benefits to this:

- More intuitive navigation.

A few times I've wanted to go to the users page and I clicked on the profile image (as you do with other apps like Twitter or Facebook). I was surprised when the issue opened instead of going to the user page. By accident I realised that you can press and hold the list item to navigate to the user profile which is a very unintuitive design choice.

- More clickable links

For example with the highlighted issue below, with the current implementation, I can click on the list item and get sent to `issue 1040` or long click the item to travel to `kedziorm`'s profile page or go to `pockethub/PocketHub`. With my proposal, you'd also be able to click on `@Meisolsson` as well.

![img_20170629_153137_176](https://user-images.githubusercontent.com/6900601/27693146-7eaccbc4-5ce0-11e7-8f56-3ac06645f4af.jpg)

<img width="656" alt="screen shot 2017-06-29 at 15 32 44" src="https://user-images.githubusercontent.com/6900601/27693151-817e2cee-5ce0-11e7-98e4-0e791bc9833e.png">

**Comment by Meisolsson** [comment]
I do agree with most of this apart from being able to click @:ed names in the text. I feel like that could make the items harder to click since most of the text now is links. And I guess that's my only problem with this as well, it's harder to click a single item in a list without hitting a completely diffrent link.

So basically I agree but also see the potential of this becoming an annoyance for users, especially for users with small phones.

**Comment by veyndan** [comment]
Wouldn't it be better just to not make the items clickable anymore as you can now just click on the associated hyperlink instead. This should address the concerns you have with the design.

**Comment by Meisolsson** [comment]
Well is that not less intuitive on phones? If given a list of items I would assume that each item is clickable and will take me the what it's talking about.

**Comment by veyndan** [comment]
Personally I think it'd be more intuitive. It's similar to Instagram where only the hyperlinks to the rest of the app are clickable. You don't just click an Instagram card and get directed somewhere.

Side note: to give a better indication that these selected items are clickable, we should make them blue.

**Comment by Meisolsson** [comment]
Alright, let's try it. But keep it to the title and image. Not the comment/body for now, still feel like that might be too much.

**Comment by BKSINGHPASS** [comment]
can you tell me how to add client id and secret key
