### ISSUE TITLE
Button to edit or delete comment shown for other users' comments

### ISSUE THREAD

**Issue by EmmanuelMess** [pockethub/PocketHub#1124]
To replicate go to an issue and press the menu (three vertically aligned dots) button for a message that's not your's.
<img src="https://user-images.githubusercontent.com/10991116/28599877-81bb63c6-7184-11e7-9f1f-4b814d068043.png" height="300px"/>
Extra info: Android 6.0; Moto E2 4G; Language Spanish; last version of PocketHub in Play Store at this date.

**Comment by Meisolsson** [comment]
Not having this bug, are you in some way admin/collaboration in repo?

**Comment by EmmanuelMess** [comment]
I didn't have access to edit the comments on GitHub from the web (I do now).

**Comment by Meisolsson** [comment]
This is fixed in master
