### ISSUE TITLE
Non existing issue found in search

### ISSUE THREAD

**Issue by Vampire** [pockethub/PocketHub#1125]
If I open https://github.com/k0shk0sh/FastHub in PocketHub and then go to issues and search for "Search", the top-most displayed issue is #1181. But when I tap on that, I'm just told that the issue could not be loaded. This is caused by the issue not existing. The question is, why it is displayed in the search results.

**Comment by Meisolsson** [comment]
Yeah, it's a bug around us not adding the repo to search. Will be fixed today.
