### ISSUE TITLE
Not available in Australia

### ISSUE THREAD

**Issue by amykapernick** [pockethub/PocketHub#1131]
It's been 7 years since this was first released and I still can't get this in the Australian Google Play store. Why?

**Comment by BKSINGHPASS** [comment]
can you tell me how to add client id and secret

**Comment by Meisolsson** [comment]
I've looked at Google Play and the app should be available in Australia. So not sure why it would be a problem, I'd say take it up with Google Play support. Sorry :/

**Comment by IzzySoft** [comment]
That's one point where it'd be helpful to have the `.apk` available here at Github (see #1035) or at F-Droid (see #948). Just saying :wink:

**Comment by Meisolsson** [comment]
Same as #1142
