### ISSUE TITLE
any api like this page？

### ISSUE THREAD

**Issue by CarGuo** [pockethub/PocketHub#1137]
hello, had any api like this page ：https://github.com/dashboard/discover ？i can't find in developer document

**Comment by Meisolsson** [comment]
Not sure what you're asking. The app doesn't have a discover feature but GitHub does.

**Comment by CarGuo** [comment]
sorry,   I just want to know if  GitHub already open such api or not.  

The app doesn't have a discover feature because no such api？

 thanks for you reply！

**Comment by Meisolsson** [comment]
Not sure, it's not what this repository is about. If you want to look further there is documentation about GitHub's api here: https://developer.github.com/
