### ISSUE TITLE
Wrong link to play.google.com in github.com/blog

### ISSUE THREAD

**Issue by eugeneloza** [pockethub/PocketHub#1142]
There's a wrong link at https://github.com/blog/1187-github-android-app-released leading to https://play.google.com/store/apps/details?id=com.github.mobile and eventually to "Sorry! This content is not available in your country yet."
![2017-12-22-192132_1366x768_scrot](https://user-images.githubusercontent.com/10726162/34306865-08bff26c-e74e-11e7-9690-6f2a93037952.png)
On the other hand, the link in README works perfectly.

**Comment by Meisolsson** [comment]
Since that blog post a lot has happened. Mainly [this](https://github.com/pockethub/PocketHub#whats-going-on-here), under `What happened to the old app?`. During this we now have a new package name, hence why the link is not functioning

**Comment by eugeneloza** [comment]
Yes, but unfortunately first link from google searching for "github android app" goes exactly there :) Maybe it's possible to refresh the link? Might be the cause of #1131 and #1139 because I just wanted to create an issue "Not available in UKRAINE" :D But before that checked the repository readme :)

**Comment by Meisolsson** [comment]
There is nothing I can do about the link since GitHub in some way has that. From what i know Google Play doesn't allow you to redirect to another app anyways. 

I could check with GitHub if they can change the link, but that will take a little wile.
