### ISSUE TITLE
Application crashes when trying to access a non existing repository

### ISSUE THREAD

**Issue by Gu1nness** [pockethub/PocketHub#1148]
When a repository has been deleted, it still appears in the list of recent events.
When trying to access it, the application crashes.

Steps to reproduce : 
 1) Install the app
 2) Log in
 3) Follow a user that deletes a repository
 4) Try to access the repository from the recent events list

**Comment by abhishekd08** [comment]
can i work on this issue ?

**Comment by Meisolsson** [comment]
@abhishekd08 Well this has a fix (#1166), just forgot to link it.

**Comment by abhishekd08** [comment]
Can you suggest any issue or work that I could contribute to ? Actually I am a beginner and searching to contribute .
