### ISSUE TITLE
Project status discussion

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1156]
This is just a general thought on increasing development speed and would like to raise a discussion about it. I was wondering if it'd be possible to bring on more people with commit access to the repository. Currently, PRs can take weeks to be accepted, meaning that many ideas that I have for the project are sitting on the back burner as they are usually dependent on the current open PRs being accepted. I have noticed that there used to be many people (and quite popular people in the Android community) that had commit access, but it seems that they have all since moved on. During the time that I have been here, I have only really interacted with @Meisolsson. While I am grateful for the active development on his part, such a project requires a greater amount of time than one person can give.

Also, with the addition of new people, code review on pull requests can take place which can hopefully reduce the amount of new bugs introduced into the app.

**Comment by Meisolsson** [comment]
I know that there is a need for faster development but a big roadblock for that has been pulling the app forward into the new libraries and throwing out old ways of doing things. Since that's done I do feel the need for more people as soon as I get a "roadmap" up for what I think the project should work towards.

**Comment by veyndan** [comment]
Thanks for making me a collaborator! Out of curiosity, am I able to merge my own PRs or should they still be reviewed first?

**Comment by Meisolsson** [comment]
Unless I'm really slow (more than 1 week) they should be reviewed. I'll try to be faster in the future.
