### ISSUE TITLE
Sign-in issue on Android 4.4.4

### ISSUE THREAD

**Issue by milo** [pockethub/PocketHub#1165]
Hi,
I would like to use PocketHub on my Android 4.4.4 but I have a sign in issue.

During an OAuth2 process, I can send username, password, 2FA code and finally, I get page with "Authorize PocketHub" access rights overview. But I cannot push the green "Authorize" button. AFAIK, the problem is, that GitHub deprecated "old browsers" (I can see such pop-overs during login message). The OAuth webpages are rendered by internal WebView. But it is hardcoded part of Android 4 (it can be upgraded since Android 5).

So, it is not the PocketHub issue at all, but I would like to know, if there is a possibility to create OAuth token by myself via GitHub webface and pass it to PocketHub app directly.

Btw. many other GitHub Android clients suffers by issues described above.

**Comment by Meisolsson** [comment]
Alright, this has already been resolved and released but looks like I forgot to roll it out to everyone. There should be an update to resolve this within the next day (version 0.4.0). If that doesn't fix it feel free to re-open this.

**Comment by milo** [comment]
Unfortunetally, still the same problem with 0.4.0. Seems to me as a JavaScript problem, because the right side slides for detailed information does not work too.

![screenshot_2018-03-01-17-33-26](https://user-images.githubusercontent.com/439140/36856750-ffb2fe4e-1d76-11e8-8bba-4b50de4fecf7.jpg)

**Comment by milo** [comment]
Would like to reopen, but I have no permissions to do it.
