### ISSUE TITLE
Remove use of Butterknife

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1178]
This issue is kind of related to #1147. @Meisolsson stated:

> When I am the first thing to be changed will be the Gropie items since the ViewHolders can be generated by the kotlin android extension.

This issue focuses on the broader idea that the Kotlin Android Extension should generate all the view bindings (instead of just for ViewHolders), ultimately making Butterknife redundant.

The two main benefits to doing this is:
* Shorter code: `@BindView` no longer needs to plague the codebase.
* Compile time type safety: accessing views in the hierarchy is typed automatically.

**Comment by Meisolsson** [comment]
Yeah, when we start moving `Items` to Kotlin we should do this. It might take another couple of week for me to get there since I have exams coming up.

**Comment by veyndan** [comment]
Would you mind if I just started converting the files containing ButterKnife annotations over to Kotlin?

**Comment by Meisolsson** [comment]
Actually, just do all of it. `Item` and the rest. I'll find other things to do later.

**Comment by veyndan** [comment]
When you say `Item` and the rest, do you mean convert every Java file to Kotlin?

**Comment by Meisolsson** [comment]
Not all of the project, just the files where we make use of ButterKnife. 

Also we should probably use the [view caching](https://kotlinlang.org/docs/tutorials/android-plugin.html#view-caching), not sure if it's in experimental or not but either way it would be good.

**Comment by veyndan** [comment]
It seems to be turned on by default, similar to how Butterknife is..
