### ISSUE TITLE
Increase minSdkVersion

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1188]
According to the [Android dashboard](https://developer.android.com/about/dashboards/index.html#Platform), only 0.4% of users are using API level 15. As this fraction of the market is so small, it'd be nice to be able to increase the minSdkVersion to be able to use newer features of the Android SDK. I feel that API 19 would be a good minimum to set, considering that will target ~95% of devices.

**Comment by Meisolsson** [comment]
Yeah, this sounds fine. From a look at the current stats of the app we have about 1% of users below API 19 so that won't cut any.
