### ISSUE TITLE
Use a code style tool for Kotlin

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1200]
This is kind of related to #1199.

As we are gradually migrating over to Kotlin, it'd be good to enforce a certain code styling. I've briefly looked around and [ktlint](https://github.com/shyiko/ktlint) seems like a good option as it enforces the official Kotlin styleguide and is popular among the Kotlin community.

As [ktlint is bound to `gradle check`](https://github.com/shyiko/ktlint#-with-gradle), it should integrate easily with Travis CI.

**Comment by Meisolsson** [comment]
Yeah, I've been looking at Klint and Detekt. But I think Detekt is only gonna be useful later when we are actually fully moved to Kotlin. Klint also tries to implement the Android Kotlin Style guide so it should be a nice fit.

So Klint is the way to go in my opinion.
