### ISSUE TITLE
Remove user avatar from Toolbar

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1206]
The toolbar with the avatar looks overly cluttered, and is reminiscent of a time pre-lollipop where having the application icon and title was common. The practice of having an application icon and title is discouraged according to the [docs](https://developer.android.com/reference/android/support/v7/widget/Toolbar.html):

> The use of application icon plus title as a standard layout is discouraged on API 21 devices and newer.

I know this isn't the application icon but the cons of having the avatar icon I feel is similar to that of the application icon.

Looking at other apps with the idea of users e.g. Facebook, Instagram, Twitter; none of them include the user icon when you are scrolling the feed, they just include the username.

Note that I'm suggesting of removing all avatar icons from the toolbar, not just the ones on the user page (e.g. also the project page, gist page).

|Current design|Proposed design|
|---|---|
|![screenshot_20180322-160704](https://user-images.githubusercontent.com/6900601/37782877-f61d0c6e-2deb-11e8-95b9-510a49005935.png)|![screenshot_20180322-160827](https://user-images.githubusercontent.com/6900601/37782878-f63a1a66-2deb-11e8-871a-be3303f6e0ef.png)|

**Comment by jfari1364** [comment]
@veyndan mind if I give this issue a go?

**Comment by veyndan** [comment]
Thanks for the interest in contributing! I'd like some feedback from @Meisolsson about this change as at the moment I'm not sure if this is a change that would be desired. If he comments saying he's onboard with the change as well, then please give the issue a go!

**Comment by jfari1364** [comment]
Not a problem at all, I'll keep my eye out and wait for the decision. I'm always up for contributing so I'll keep an eye out on the issues portion of this repo.

**Comment by Meisolsson** [comment]
It's good to remove it now, but later we probably want something like with a user info and avatars in a AppBarLayout. But yeah, removing it sounds good.
