### ISSUE TITLE
Remove loading text when scrolling to bottom

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1214]
Currently when the user scrolls to the bottom of the page, a progress bar and text stating that the items are being loaded is present. The text stating that items are being loaded is unnecessary and adds clutter to the app design. Many other popular apps just use the progress bar with no text, which I feel is a lot cleaner and should be adopted by this app.

Another benefit (though less important) is maintenance of page loading strings in other languages is no longer needed as a progress bar is universally understood.

|PocketHub|Instagram|Twitter|Facebook|
|---|---|---|---|
|![old](https://user-images.githubusercontent.com/6900601/38001317-0b8eac1a-3224-11e8-975d-c247e0ce74b8.png)|![ig](https://user-images.githubusercontent.com/6900601/38001324-10b9657c-3224-11e8-8727-961d44f27af7.png)|![twitter](https://user-images.githubusercontent.com/6900601/38001327-15f1707a-3224-11e8-89df-87795a648e07.png)|![fb](https://user-images.githubusercontent.com/6900601/38001338-1d64b736-3224-11e8-8392-2df63ee86e56.png)|

**Comment by Meisolsson** [comment]
Not much to say, sounds like a good idea. Feel free to do it.

**Comment by surajdubey** [comment]
I can submit PR for this @veyndan @Meisolsson 
Let me know if I should start on it.

**Comment by veyndan** [comment]
Sure go for it!
