### ISSUE TITLE
Cannot authorize on Android 4.3

### ISSUE THREAD

**Issue by Suncatcher** [pockethub/PocketHub#1217]
Authorization fails when I press sign-in. Seems stock Android browser is nott supported.
I have latest Chrome installed on my tablet, why it not prompts to choose it?

![screenshots_20180330_105501](https://user-images.githubusercontent.com/6388034/38129890-870c70ca-3409-11e8-9bad-f61286bee39e.png)

**Comment by Meisolsson** [comment]
We have recently dropped that version of Android so there's nothing I can do with this.
