### ISSUE TITLE
New search from search results view doesn't work

### ISSUE THREAD

**Issue by mjaseem** [pockethub/PocketHub#1218]
On search results view, if you start a new search by entering a new query, page will reload and but will show the old results. To make a new search successfully you have to first get out of the search results view. This is happening for both Repository and User search.

### How to reproduce:
1. From home, press on search icon enter a query string and press enter.
2. Once the results load, click on the search icon again, enter a new query string and press enter. Search results won't change.

I have a fix for this so please assign it to me.

**Comment by veyndan** [comment]
You don't need to be assigned this, please feel free to just make a PR.

**Comment by doomtrooper** [comment]
is this still open?
