### ISSUE TITLE
Icon/Logo Design Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [pockethub/PocketHub#1224]
Hi Sir @fadils  Sir @Meisolsson , Good day! I am a graphic designer and i want to contribute to your awesome project by proposing a new icon/logo design. If you like it i will be gladly sending you the needed files as a gift for free..

Here is the design:

![design idea](https://user-images.githubusercontent.com/36028424/39519972-72882b66-4e3b-11e8-987f-ce29affd2cf1.png)

app icons
![pockethub-01](https://user-images.githubusercontent.com/36028424/39510975-4f9965f6-4e1e-11e8-948e-ef5d91fd9848.png)
![pockethub-02](https://user-images.githubusercontent.com/36028424/39510976-5276b63e-4e1e-11e8-856a-8e2bf63b199e.png)

logotype A
![pockethub-03](https://user-images.githubusercontent.com/36028424/39510980-5aaa8a74-4e1e-11e8-90d7-f344d2d752c0.png)
![pockethub-04](https://user-images.githubusercontent.com/36028424/39510981-5adfc568-4e1e-11e8-8eda-b8b188b0efd4.png)

logotype B
![pockethub-05](https://user-images.githubusercontent.com/36028424/39510994-619e79b2-4e1e-11e8-9081-0103a44543b0.png)
![pockethub-06](https://user-images.githubusercontent.com/36028424/39510995-61d9c940-4e1e-11e8-83d4-8959934a5dbc.png)

if you liked it or you have any additional suggestions just inform me and i will edit it for you.

Hoping a positive feedback and best regards to the project!
-tobaloidee

**Comment by netflair** [comment]
I like it, looks really good

**Comment by Tobaloidee** [comment]
Thanks for the positive feedback Sir @netflair ,much appreciated.. I'll be readying the files asap if it will be used.

**Comment by veyndan** [comment]
I like it! I'm not sure whether we would want to change the icon colour (and hence the app colour) to be more aligned with the material colours. That's probably cause for a greater discussion though. 

Also just to note, this is related to #905.

**Comment by Tobaloidee** [comment]
Even if you picked the one color that you prefer I would still send you all these variations so that you can use it in future purposes.

**Comment by Tobaloidee** [comment]
I will be waiting for you feedbacks Sirs. best regards!

**Comment by Meisolsson** [comment]
@Tobaloidee For now the orange and the grey would be awesome. The orange one would be used for debug builds.

@veyndan I've created an issue around changing the theming of the app and we can discuss color there. #1225

**Comment by Tobaloidee** [comment]
Okay Sir..i'll stay in touch here until the color has been decided.. :)
