### ISSUE TITLE
Invalid link in play store description

### ISSUE THREAD

**Issue by bukzor** [pockethub/PocketHub#1227]
Clicking the link to this repo in the Google play store "Description" section gives a 404.

Context: https://play.google.com/store/apps/details?id=com.github.pockethub.android

![screenshot_20180618-074503](https://user-images.githubusercontent.com/640328/41543609-fd970e16-72cb-11e8-9ba4-fea8c9b80f96.png)

**Comment by Kyle-P** [comment]
Seems to work fine now!

**Comment by Kyle-P** [comment]
Looks like your error came from including the period in the URL.

**Comment by Meisolsson** [comment]
This has been fixed now.
