### ISSUE TITLE
Crash when viewing others' repos.

### ISSUE THREAD

**Issue by githubcatw** [pockethub/PocketHub#1233]
## Description
A concise description of what the problem is.
When I open a repository that is not mine, the app crashes. However, I can still view issues linked with URLs.

### Versions and device
What version of the app does this happen on?
0.4.0
Was the version downloaded from the Play Store?
yes
What version of Android does it happen on?
8.0 (Oreo)
What model of phone does it happen on?
Samsung Galaxy S8 (SM-G950FD)

## Steps to Reproduce
1. Open one of the currently logged in user's repos.
2. Observe the app not crashing.
3. Open one of the user's friends' repos.
4. Observe the app crashing.
5. Open another, non-related user's repo.
6. Observe the app crashing.

### Actual behaviour
The app crashes on the last 2 repos.

### Expected behaviour
All 3 repos open.

## Logs
I tried these steps with MatLog Libre running, here is the result (logcat): https://drive.google.com/file/d/1WjOlXXd3oWtOtOX4Fah7wzkfFXbLOKgg/view?usp=drivesdk

**Comment by Meisolsson** [comment]
There will be a new version available within a day which should fix this issue. If your issue is not fixed by it please reopen the issue.
