### ISSUE TITLE
README.MD must have the details about how to run this code on developing platform 

### ISSUE THREAD

**Issue by iamkanhaiya** [pockethub/PocketHub#1242]
As this app is developed in scratch , if someone want to contribute in it using his/her scratch developing skills or a person who want to learn how this code works. He/She must know how to run this code on platform and which platform he/she can choose to run this and rebuild this. 

so its a advice that pockethub must add the details about how to run this code on developing platform in README.MD.

**Comment by SaumyaSingh1** [comment]
can I take up the issue ?

**Comment by Meisolsson** [comment]
Sorry but I don't understand the question. The project is meant to be built and developed using Android Studio.
