### ISSUE TITLE
Remove random gist button

### ISSUE THREAD

**Issue by veyndan** [pockethub/PocketHub#1268]
The "Random" button in the toolbar of the "Gists" screen should be removed. Returning a random gist almost always gives me a gist that is fairly meaningless to me as the gists use a very specific technology, language, or field that I have no knowledge about and/or care about. Removing this will remove some clutter from the app, as well as reducing the amount needing to be maintained.

**Comment by Meisolsson** [comment]
Yeah, go for it.
