### ISSUE TITLE
Create List of repositories/people in Android App

### ISSUE THREAD

**Issue by 18bytes** [pockethub/PocketHub#132]
When we follow many people/watch repositories there is overwhelming amount of  information in the Newsfeed. 

It would be great if we can create userdefined categories in the Android app (Will be nice if we can create categories in the webinterface as well). After creating the categories, we can see the news feed for each category.

**Comment by EzraBrooks** [comment]
I'm not sure this is within the project scope, as it isn't available in the web interface to my knowledge.

**Comment by Meisolsson** [comment]
This will not be implemented
