### ISSUE TITLE
Who owns what? 

### ISSUE THREAD

**Issue by jfeldstein** [pockethub/PocketHub#159]
I want to see how everyone on my team is progressing, but all the icons are my face (sonic the hedgehog) because I comment a lot.

It'd be nice to see who owns what from the list view, without needing to open each.

![screenshot](http://cl.ly/image/1T0C3h3a3q30/content)

**Comment by EzraBrooks** [comment]
I think we should switch to doing it the way the web interface does - show the author after the issue name, not the most recent commenter.

@fadils, @Meisolsson, what do you think?

**Comment by Meisolsson** [comment]
From what I can see we show the author already. So this should be closed.

**Comment by jonanp** [comment]
I think this issue is about showing the assignee not the author. I don't know if it's a good idea though.

**Comment by Meisolsson** [comment]
Not clear what is asked, if you find it a problem with the PocketHub app create a new issue.
