### ISSUE TITLE
strange behavior when changing githubusername

### ISSUE THREAD

**Issue by airatshigapov** [pockethub/PocketHub#172]
Firstly i logged in to my android github client with username "X", and after some time i changed it to "Y", and after that my android client didnt work properly, told me about authenication problems. After re-installing and reloginning with my email problem is still there. The problem was solved by reinstalling again and reloginning with my new github username, but i think it should work without reinstalling and with reloginning with github username too, not with just email!

**Comment by larsgrefer** [comment]
since we use oauth, this shouldn't be a problem anymore.
we should close this issue
