### ISSUE TITLE
Cannot focus username/email box when username changed

### ISSUE THREAD

**Issue by thiderman** [pockethub/PocketHub#201]
I recently changed my username. When I did, I was logged out from the Android app and presented with a login form, with my old username understandably pre-filled. However, there was no way at all to focus the username input and change it.

I had to reinstall the app to be able to log in.

I'm on a Samsung Galaxy S2 with the latest firmware, and I was running the latest version of the Github client available at Google Play.

**Comment by Meisolsson** [comment]
This should not be an issues as we new depend on GitHub's web auth flow
