### ISSUE TITLE
Source code cut off

### ISSUE THREAD

**Issue by joseds** [pockethub/PocketHub#222]
Hi, 
thank you for adding the ability to browse source code, that's a very useful feature. I noticed that only part of the code is being displayed,  I had e.g. 101 lines in one and 201 lines in another case. Is this limit perhaps character count based? 
Source code browsing would not be very useful for me if such a cut–off exists. Is this a bug or is there a strong reason behind it? 
José

**Comment by guotong1988** [comment]
landscape!
