### ISSUE TITLE
Remove Gist # on Gist Dashboard

### ISSUE THREAD

**Issue by mattgraham** [pockethub/PocketHub#27]

**Comment by veyndan** [comment]
The gist id adds no value when scrolling through the list, and this issue never discusses the decision as to why it was kept. The readability of the items greatly increases when the ids are removed, as they are just adding visual clutter and making each item taller for no real benefit. Thoughts @Meisolsson?

|Before|After|
|---|---|
|![before](https://user-images.githubusercontent.com/6900601/66317225-ff17a900-e910-11e9-98a3-e752af1100c9.png)|![after](https://user-images.githubusercontent.com/6900601/66317232-017a0300-e911-11e9-9b49-60f5c18af30e.png)|

**Comment by Meisolsson** [comment]
Yeah, we can remove that. Serves no real purpose for us
