### ISSUE TITLE
Add language selection

### ISSUE THREAD

**Issue by ironjan** [pockethub/PocketHub#304]
The German translation is often confusing and there are many phrases that do not have a non-misleading German counterpart. Since the github homepage is not localized, localization of the app seems not necessary to me.

Thus I would suggest to either drop localization or empower the user to select the app language.

**Comment by larsgrefer** [comment]
The german translation was updated in #758, #801, #855 in order to be less confusing.
I think we can close this

**Comment by ironjan** [comment]
Quick-Checked the translations via string.xml and did not encounter very misleading strings (I seem to remember that "issues = probleme" was one of the translations). Sorry that this issue was so unspecific.
