### ISSUE TITLE
Editing comments on issues should be possible

### ISSUE THREAD

**Issue by ironjan** [pockethub/PocketHub#309]
What is happening? How to reproduce?
1. Open an issue you commented on
2. Try to edit your comment
3. Editing a comment is not possible since there is no control to do so

What would I expect to happen?
3. A control to edit own comments should be shown.
4. Editing the issue should be possible

Additional info:
The issue was created by myself. I could edit the issue.

**Comment by Meisolsson** [comment]
Editing of comments is possible, this was never closed.
