### ISSUE TITLE
comments in commits neither loading nor being counted correctly

### ISSUE THREAD

**Issue by mcilloni** [pockethub/PocketHub#366]
I am using the last version of the application from the play store. I have noticed that it's always showing zero comments in any commit in a private repository (I've not tried with public ones). if I try to open the commit, comments are simply not loaded. if I post a comment, it briefly stays on bottom then it just disappears. I am using android 4.2.2 on the nexus 4.

**Comment by Meisolsson** [comment]
Fixed
