### ISSUE TITLE
Support creating new GISTs by sharing from other apps

### ISSUE THREAD

**Issue by mbirth** [pockethub/PocketHub#375]
When sharing a Tasker XML and selecting "XML in Email", I can not only select *Gmail*, but also *Add to Dropbox* or *Box.net*. I'd love to also being able to select *GitHub GIST* which would create a new GIST with the shared contents.

![Tasker Export Intent](https://f.cloud.github.com/assets/130302/623824/86c4578a-cf74-11e2-9024-6dfd99922975.png)

**Comment by EzraBrooks** [comment]
I agree, this is a great idea.

**Comment by larsgrefer** [comment]
@mbirth can you provide any information about what kind of intent the other app fires?

**Comment by mbirth** [comment]
@larsgrefer It's a standard `android.intent.action.SEND` intent. The log shows:

    START u0 {act=android.intent.action.SEND typ=text/xml flg=0x1 cmp=android/com.android.internal.app.ResolverActivity clip={text/xml T:<TaskerData sr="" dvi="1" tv="4.7u3m">

**Comment by larsgrefer** [comment]
At the moment the App catches only `SEND` intents with MIME type `text/plain` : https://github.com/pockethub/PocketHub/blob/master/app/src/main/AndroidManifest.xml#L55

It may be better to catch `text/*`
