### ISSUE TITLE
Enabling two factor authentication breaks sign in

### ISSUE THREAD

**Issue by jgreet** [pockethub/PocketHub#404]
If a user has enabled two factor authentication for GitHub they are no longer able to sign in to the app. Existing sessions will still work.

**Comment by lig** [comment]
Seeing this error again on Android 5.0. Latest Github app. Was able to auth on site, but cannot in app.

**Comment by hzsweers** [comment]
Are you running the latest master? If it's from the store, the last version
github uploaded wasn't able to handle their new auth scheme

**Comment by lig** [comment]
@hzsweers well, this means the only one thing. There is no working version released. Ok then.

**Comment by hzsweers** [comment]
Yes, we're pretty clear about that in the README.

**Comment by lig** [comment]
@hzsweers Thank you very much for the answer! It is the great news. Looks like the original app should just be removed from the Google Play. What a shame for Github team.

Again, thank you and keep up the good work!

**Comment by traveller42** [comment]
Thanks for the info.

GitHub app has been removed from my devices.

**Comment by dpq** [comment]
You can disable TFA, log into your github account on your phone and reenable TFA if you prefer to quickly fix things on your side.

**Comment by moritzschaefer** [comment]
This is still an issue for me!

**Comment by hzsweers** [comment]
Please include details of what you tried, that is not enough information to help.

**Comment by moritzschaefer** [comment]
Login with GitHub Android App fails when entering the 2 factor key (I use authy)
It accepts the password, then asks me for the PIN, I copy it from authy and it says "wrong password" throwing me back to the login-widget

Login on mobile website works without problems.

**Comment by hzsweers** [comment]
And this is built from master or the old GitHub app?

**Comment by moritzschaefer** [comment]
This is from play store. As the last message was from Nov '15, I thought this bug got forgotten.

**Comment by hzsweers** [comment]
Read the README and CONTRIBUTING.

**Comment by SparK-Cruz** [comment]
Authorize button is insensitive now, can't login. I didn't (and won't) try disabling 2FA but I wonder if it's related.

**Comment by harel** [comment]
2017 - the bug that keeps on bugging. Cannot use the app since 2FA is on. This is still an issue, latest Android 8, Nexus 5X.

**Comment by phothargbk** [comment]
https://github.com/sessions/verified-device/mobile?auto=true
