### ISSUE TITLE
request: add merge button for pull request

### ISSUE THREAD

**Issue by MartijnKaijser** [pockethub/PocketHub#520]
currently there is only a close pull request button. a merge button that show to which branch you want to merge (with confirmation of course) would be great

**Comment by adamgeorgeson** [comment]
:+1:

**Comment by hzsweers** [comment]
That and the option to delete the branch afterward

**Comment by bdunogier** [comment]
Still valuable ! :)

**Comment by SFarageNIS** [comment]
:+1:
