### ISSUE TITLE
Search Bar Addition

### ISSUE THREAD

**Issue by mananwason** [pockethub/PocketHub#688]
After I search something, if I wish to slightly change the text searched, I have to rewrite the whole thing. it would be nice if we could just change the existing search text. 
Would you be open to this change?

**Comment by OrangeFlash81** [comment]
:thumbsup:

**Comment by danielFerecatu** [comment]
great idea :+1:

**Comment by Oucart** [comment]
great!

**Comment by mananwason** [comment]
Good, then I'll start working on it then

**Comment by weric** [comment]
@jonan I can't make your commit work on emulator HVGA slider API 21.Can you show the screenshots?

**Comment by jonan** [comment]
This feature is already working on [ForkHub](https://github.com/jonan/forkhub). You can download it and give it a try.

@weric Simply make any search and then press the search button again, you'll see the search bar containing your previous search.

**Comment by Meisolsson** [comment]
Implemented in #1024
