### ISSUE TITLE
Labels are not shown in pull requests

### ISSUE THREAD

**Issue by jonan** [pockethub/PocketHub#727]
When you load a pull request you can initially see the labels, but when it fully loads and the view refreshes, the labels disappear.

**Comment by jonanp** [comment]
Investigating the issue I've seen it's a bug in the API library.
It also needs a change in the app, but it can't be done until the library is updated.

I've started fixing some of the issues in the API library, if upstream accepts them we might be able to fix this kind of issues soon.

**Comment by Meisolsson** [comment]
Looks like this has been fixed!
