### ISSUE TITLE
Add native Android notifications

### ISSUE THREAD

**Issue by tych0** [pockethub/PocketHub#74]
It would be cool if we could have native android notifications (either push or some custom polling interval) which would mirror github notifications.

Yes, I get them via email, but I refuse to check my email on my phone. Interesting things actually happen on github, so it would be nice to have notifications of them :-)

**Comment by litera** [comment]
ZenHub anyone? It would make this *thumbs up/+1* much easier.

**Comment by danielFerecatu** [comment]
+1

**Comment by bhack** [comment]
Anybody interested in this feature can try https://github.com/Daskiworks/ghwatch

**Comment by ryanwalls** [comment]
+1

**Comment by Meisolsson** [comment]
See #196 for further discussion
