### ISSUE TITLE
'GitHub' Name and Logos

### ISSUE THREAD

**Issue by larsgrefer** [pockethub/PocketHub#771]
@kevinsawicki @jonan @fadils  Are we still allowed to use the 'GitHub' Name and Logos (https://github.com/logos) since the app is not official anymore?

**Comment by kevinsawicki** [comment]
I'm not sure of the answer to that at this time. I'll look into it and get back to you.

/cc @talniv

**Comment by fadils** [comment]
Thanks @kevinsawicki

**Comment by hzsweers** [comment]
@kevinsawicki any luck on this? At most I think we would maybe want to use the mark. We can get by on new names.

![](https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png)

**Comment by larsgrefer** [comment]
@hzsweers If we are allowed to, i can provide properly sized versions of this mark (24dp with 20dp diameter and 48dp with 44dp diamenter)

**Comment by hzsweers** [comment]
Yeah adjusting sizing shouldn't be a problem

**Comment by larsgrefer** [comment]
I've already done the sizing, so it would be very easy for me

**Comment by EddieRingle** [comment]
Odds are you will not be able to use the Octocat or GitHub marks as this is no longer the official application. At least, that was GitHub's position according to @defunkt a long, long time ago when I was still actively working on Hubroid.

**Comment by larsgrefer** [comment]
@kevinsawicki Do you have any new information about this?

**Comment by kevinsawicki** [comment]
No, sorry I don't.

I think following the instructions on https://github.com/logos is probably best moving forward.

**Comment by larsgrefer** [comment]
So we are not allowed to use the github mark
