### ISSUE TITLE
Consistent Navigation

### ISSUE THREAD

**Issue by timroes** [pockethub/PocketHub#79]
You can use a spinner in the start screen to choose between your different organisations and gists, issue dashboard, etc. If you are on Issue Dashboard or gists, there is no spinner anymore, but an Up-Button. In my oppinion this is inconsistent behavior. There should be a spinner in all screens thst you can reach by a spinner option. I would be interested in the oppinion of other users about that topic.

Edit: I also recognized, that there is no Up functionallity in the issue view. In the issue list there is still one, so I think there should also be an Up functionallity in the issue view, bringing you up to the issue list.

**Comment by EzraBrooks** [comment]
Hi all you who have agreed with this issue, can you read the [guidelines](https://developer.android.com/design/patterns/navigation.html) for Navigation with Back and Up and cite where the app doesn't comply? Since there's a lot of design work being done anyway, now seems a good time to fix this.

**Comment by veyndan** [comment]
Closing as spinner is no longer a part of the app
