### ISSUE TITLE
Android SDK

### ISSUE THREAD

**Issue by alorma** [pockethub/PocketHub#792]
Hi, i'm developing GitSkarios, and of part of it i uses Retrofit.

I see that you are trying to use retrofit in gforkhub api.

I will provide you to my GithubSDK: https://github.com/gitskarios/GithubAndroidSdk

Feel free to look at it, use it or make me pull requests or open issue!

**Comment by hzsweers** [comment]
Awesome! Thanks for the help, will definitely look at helping improve that SDK

**Comment by larsgrefer** [comment]
Using retrofit could help us implementing #14. Just using different API endpoints

**Comment by Meisolsson** [comment]
Just so we set a clear path, would we like to use this or build our own? I have not yet checked by I guess this one uses the new auth so we don't have to implement that.

**Comment by fadils** [comment]
I'm more into reusing what @alorma has already built..
I will probably test it this weekend.

**Comment by Meisolsson** [comment]
It looks like he's using the Web Application auth. So the question is if we want too redirect our users to the website or if we want to do the auth ourselves without the web flow and then use the SDK?

**Comment by Meisolsson** [comment]
I got it working last week but then I took a bit of water over my head... Tried to update alot of the main calls to the SDK and got lost. But I have it working again.

However there are two problems:

1. We need to have the codes for a GitHub application in the app (Everyone needs their own).
2. The libs are not files so we need the projects as modules in the app (BaseSDK could be a file).

**Comment by alorma** [comment]
Maybe, you can generate your own AAR, but as i need them, and i'm developing that, i need as modules

**Comment by Meisolsson** [comment]
Yeah I know, just pointing out the problems I saw while doing it.
On Jun 18, 2015 19:40, Bernat Borrás Paronella <notifications@github.com> wrote:Maybe, you can generate your own AAR, but as i need them, and i'm developing that, i need as modules

**Comment by fadils** [comment]
@Meisolsson @alorma 

Perhaps [jitpack](https://jitpack.io) will come handy?

```GROOVY
repositories {
  ...
 maven {
    url "https://jitpack.io"
  }
}

dependencies {
  ...
  compile 'com.github.gitskarios:GithubAndroidSdk:v.1.5.0'
}
```

**Comment by Meisolsson** [comment]
That look like a good solution, will test it later. :+1:

**Comment by alorma** [comment]
Mmm.

If you need to upload it, should be me who uploads into *binary center like
jcenter etc..., isn't?

**Comment by Meisolsson** [comment]
Well it's not uploading, it copies the lib directly form GitHub and compile on the client. If I understand correclty

**Comment by alorma** [comment]
Oh. I read about that, looks cool!

I will try later today, i will try to create a release and publish there

**Comment by fadils** [comment]
@Meisolsson correct!

**Comment by alorma** [comment]
Oh sorry, didn't read before :)

So, the sdk needs the ability to be compiled independent, right?

**Comment by Meisolsson** [comment]
Looks like it, I see a problem right there. Since it needs the codes

**Comment by fadils** [comment]
Have you guys tried it?

**Comment by Meisolsson** [comment]
Yeah but he need to add some specific stuff to his project. It won't work otherwise

**Comment by alorma** [comment]
Make a PR and i will test today later

**Comment by Meisolsson** [comment]
I if get it working I will

**Comment by Meisolsson** [comment]
Since it compiles on the server I can't give it the codes. But I have a better way for you to get the codes which would let us use a compiled version. If u use Manifest meta-data (http://developer.android.com/guide/topics/manifest/meta-data-element.html) you could just release a .aar or use JitPack. 

It's up to you but would make using your lib easier.

**Comment by alorma** [comment]
how you will manage the metadata?

**Comment by hzsweers** [comment]
There's a gradle plugin called bintray-release that makes uploading to
bintray (and by extension jcenter) really easy

**Comment by Meisolsson** [comment]
The meta-data is in the mainfest for each app, when you call for it in the lib it gets it from the apps manifest. I think Google uses it for their ads lib, so you can look at that. I have a woking copy in locally for the moment.

**Comment by alorma** [comment]
yes maybe...

I know how meta data works, the problem there is that i don't want to publish credentials there

**Comment by Meisolsson** [comment]
Well could you not just have them in a string file which is local?

**Comment by alorma** [comment]
Well, create a PR with that changes, tell me which file i should create, and i will check :D

PD: Mod the `.gitignore´ file too

**Comment by alorma** [comment]
I made an update of how credentials are load into the SDK.

https://github.com/gitskarios/GithubAndroidSdk/commit/b76e2135b8925ec5720ef1b4ef219e5f6ce1beee

I will add a defult CredentialsProvider, and upload a new version to the Bintray

**Comment by hzsweers** [comment]
Does that help with the org permissions issue? (Not being able to write
anything to group orgs)

**Comment by alorma** [comment]
What you mean? I have problems commenting on this issue from the app :s

**Comment by hzsweers** [comment]
Ah, nevermind it doesn't. 3rd party apps permissions with orgs

**Comment by fadils** [comment]
GitHub SDK is merged. Closing this issue.
