### ISSUE TITLE
support for Pull Requests

### ISSUE THREAD

**Issue by rtyley** [pockethub/PocketHub#8]
Creating new pull requests: this is potentially a bit more meaty than supporting issues... require you to have a forked repo setup on GitHub so you can point the recipient at it to show them the available changes. Potentially you could have that repo already setup, and just select a source and target branch to initiate a new pull request... it would be really nice to get some Agit-style device-based-git in place so that you can do rebases...

**Comment by Meisolsson** [comment]
Moving to #663
