### ISSUE TITLE
Support BUCK build

### ISSUE THREAD

**Issue by fadils** [pockethub/PocketHub#803]
I'm just a new fan. It's fast. But I mean, it's really fast.

**Comment by hzsweers** [comment]
It is fast, but based on the premise of splitting everything up into very tiny decoupled modules. With Gradle's parallel build flag, IIRC their speeds are relatively equivalent. Are your build times slow?

**Comment by fadils** [comment]
VERY. 
What's your thread number?

**Comment by fadils** [comment]
I mean, if it can perform at least comparably, I would not waste more time integrating Buck.

**Comment by larsgrefer** [comment]
>Note: Buck works only on Mac OS X and Linux. Windows is not supported.
(https://facebook.github.io/buck/setup/quick_start.html)

**Comment by larsgrefer** [comment]
I think we should keep gradle, because
- its fast enough
  - preDexing (#887)
  - Gradle Daemon (https://docs.gradle.org/current/userguide/gradle_daemon.html)
- its the preferred build system and supported by google
