### ISSUE TITLE
Move towards using Appcompat's new design library?

### ISSUE THREAD

**Issue by Meisolsson** [pockethub/PocketHub#818]
Since the new design part has more native things and simpler usage for some of the animations.
Source: https://www.youtube.com/watch?v=32i7ot0y78U

**Comment by hzsweers** [comment]
Absolutely, definitely want to do this.

**Comment by sank20** [comment]
Hi, I would like to work on this issue. Is there any list of views/ UI that need to be upgraded to new design libraries or may I pick my choices ?
