### ISSUE TITLE
404 on username change

### ISSUE THREAD

**Issue by lbarrios** [pockethub/PocketHub#819]
I changed my username, so for example all my repositories changed from github.com/oldusername/repo to github.com/newusername/repo.

In the github android app, then, in the repositories section, I can view all my old repositories (created before the username changed), and I can click and view into their content, but I can't see any of the repositories created AFTER the username change.

I think the problem is that after a username change,  github maintain a redirection from old urls (with the old username) to new urls. So surely the app is trying to access the old username repositories..

Anyway, when i do "refresh" in any of the sections, a little 404 popup appears.

**Comment by aashrairavooru** [comment]
I tried logging in the first time today and got a 404

**Comment by hzsweers** [comment]
Aashrai please see CONTRIBUTING.md. your issue is not related to this one.
