### ISSUE TITLE
Inner task in fragment might cause memory leak

### ISSUE THREAD

**Issue by peacepassion** [pockethub/PocketHub#820]
In the [RepositoryCodeFragment.java](https://github.com/peacepassion/android/blob/master/app/src/main/java/com/github/mobile/ui/code/RepositoryCodeFragment.java), there is a none-static inner task `RefreshTreeTask` started in the none-mainUI thread. It refs the fragment and the attached activity. I think when the screen rotation happens, the old activity and fragment failed to be gc. 

Please help check this problem.

**Comment by hzsweers** [comment]
Will do, thanks!

**Comment by StefMa** [comment]
According to [this](http://android-developers.blogspot.de/2009/01/avoiding-memory-leaks.html) , we can fix this with [Context#getApplicationContext()](http://code.google.com/android/reference/android/content/Context.html#getApplicationContext())

**Comment by hzsweers** [comment]
The long term plan for this is to use RxJava/RxAndroid and bind long running background tasks to the lifecycle of the containing activity/fragment/view. We'll fix it once there, rather than playing wack-a-mole here first.

**Comment by Meisolsson** [comment]
Since #1011 this should be fixed since I moved most of the tasks to RxJava.
