### ISSUE TITLE
Document what goes into github.properties

### ISSUE THREAD

**Issue by pfn** [pockethub/PocketHub#845]
What are, and how do we define:

`github_oauth`
`github_oauth_scheme`
`github_secret`
`github_client`

Is it ok that they are just left to `DEFAULT`?

**Comment by Meisolsson** [comment]
When they are DEFAULT it won't login. 

I will change the install guide later today, forgot it when creating the PR

**Comment by Meisolsson** [comment]
Until I fix it here's the steps.

1. You need to create a github application (https://github.com/settings/applications/new)
2. Create a github.properties in the root folder of the repo
3. Add these three value too the github.properties

```
GITHUB_CLIENT=your_application_client_id
GITHUB_SECRET=your_application_client_secret
GITHUB_CALLBACK=your_callback_url
```
(The callback url need to be in the format "your_schema://whatever_you_want")

**Comment by alorma** [comment]
Hey

If you are using GithubAndroidSdk from @alorma,

I changed how properties can be loaded.

Now, it supports manifest and buildconfig, or you can use a file, etc.

I will upload a new release to bintray today afternoon.

**Comment by alorma** [comment]
I added a gitter chat for discuss Android SDK

https://gitter.im/gitskarios/GithubAndroidSdk

**Comment by Meisolsson** [comment]
It's added to the README so I'll close this now
