### ISSUE TITLE
Cannot login with 2FA

### ISSUE THREAD

**Issue by chaim1221** [pockethub/PocketHub#854]
Android 5.0.1
Kernel 3.4.0
Build LRX21Y
Version 1.9.0

Steps to reproduce:

Enter a valid GitHub login name (in my case, the one I'm posting with here) and password for an account set up with 2FA. Click Done on keyboard (no button provided). App says "Logging in..." and then asks for 2FA code. Switch to Authenticator, retrieve code via copy+paste or memorization (doesn't matter, they both fail) and enter it.

Expected result: Logged in to GitHub for Android.

Actual result: Returned to login screen with a message, "Please enter a valid login & password".

**Comment by Meisolsson** [comment]
Are you using the Play store version? It's very outdated...

Also please check for earlier issue since this has been brought up berfore

**Comment by chaim1221** [comment]
I did search for "login" related issues, but I didn't find anything having to do with 2FA. Has this been fixed? It's still happening in the app.

Yes, I'm using the Play store version. When you say "it's very outdated" --Why isn't it being updated?

**Comment by Meisolsson** [comment]
Read the README, we try too explain it there. And yes it's fixed in the current master branch and we are working on a new release.

**Comment by chaim1221** [comment]
K. I did read the README but I didn't think it said anything about switching apps if we already have the Play store version. In any case, I'll close this.
