### ISSUE TITLE
Button to access Readme.md directly

### ISSUE THREAD

**Issue by jahd2602** [pockethub/PocketHub#860]
When exploring github.com for new projects, one can know what is the project about by scrolling and taking a glance at the readme.md part of the page.

In the app, there should be an action bar button (or elsewhere) in the repository activity that would open the readme.md directly.

Current steps are:
1. Open repository
2. Go to code tab
3. Scroll and look for readme.md
4. Open readme.md
5. Read the description of the repository

Suggested steps are:
1. Open repository
2. Tap on the action bar button: Readme.md
3. Read the description of the repository

**Comment by Meisolsson** [comment]
I have some other ideas in mind but it will become easier. As soon as we get the application released

**Comment by StefMa** [comment]
@Meisolsson i have beginning some things. Can you look in #966 ? Is this equal to your ideas?! :)

**Comment by hzsweers** [comment]
@stefma I meant copy your content from there to here, so we're not discussing in separate threads

**Comment by jahd2602** [comment]
@StefMa I really like that idea! Maybe 5 tabs would look a little tight in that space. But I may look ok with a scrolling tabs navigation (as in Google Play).

Also, my original idea of the action bar button may not be the best one, because some repositories have long names and they would collide with the Readme.md button.

**Comment by vyasgiridhar** [comment]
@jahd2602  Are you still working on this idea?

**Comment by jahd2602** [comment]
Not really, I'm waiting for "the application to be released".

**Comment by Meisolsson** [comment]
Sorry for the wait, I've had school etc. I'm back and hoping to release this weekend. The feature we are talking about here is implemented in #1005. Had the time to sit down with it yesterday.

**Comment by Meisolsson** [comment]
#1005 has been merged so I'm closing this
