### ISSUE TITLE
App Conflict in Android Emulator

### ISSUE THREAD

**Issue by joelchen** [pockethub/PocketHub#862]
From a fresh installation of Android Studio 1.3, running the app in the built-in Nexus 5 API 22 x86 Emulator will encounter the following issue:

![screen shot 2015-08-06 at 4 54 07 pm](https://cloud.githubusercontent.com/assets/6938607/9108394/60671d2e-3c60-11e5-9164-2cdcbc1e8691.png)

**Comment by hzsweers** [comment]
This makes sense. The application ID changed, you'll need to remove the old version first.
