### ISSUE TITLE
scala file not parsed

### ISSUE THREAD

**Issue by vmarrazzo** [pockethub/PocketHub#864]

**Comment by Meisolsson** [comment]
An example repo and file to test on?

**Comment by vmarrazzo** [comment]
https://github.com/vmarrazzo/compareBuild/blob/master/ch4ex1.scala

on my Samsung Galaxy S3 I see this file like a text one without highlight on code keyword

**Comment by fadils** [comment]
@vmarrazzo This has been addressed in #603.
Also, I just tried on Genymotion S3. It seems to work fine.

![screen shot 2015-08-27 at 8 06 25 pm](https://cloud.githubusercontent.com/assets/6204776/9521154/456cc35a-4cf7-11e5-9588-52abe5e6a00e.png)

Could you please share your screen shot?

**Comment by vmarrazzo** [comment]
Here attached the screenshot with my Galaxy S3
Android version 4.3
GitHub App version 1.9.0

![screenshot_2015-08-28-08-47-27](https://cloud.githubusercontent.com/assets/4218094/9540738/2f9d7b08-4d62-11e5-9e88-46f8122e9f88.png)

**Comment by fadils** [comment]
> GitHub App version 1.9.0

Please use the current master.

Closing this for now.

I'll reopen if this still happens.

**Comment by vmarrazzo** [comment]
Actually the Google Play contains this version.

Where can I get the built app with current master without building it?

**Comment by Meisolsson** [comment]
For the moment we don't have one. We are working on a RC but it will take a while
