### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by Damonzh** [pockethub/PocketHub#865]
when i first run app on my device ,i got this error "Another installed app is already configured for GitHub authentication.You must remove the other app from the Accounts ; sync settings and uninstall it before the GitHub app can be used." but i never install GitHub App before and i can not remove that app. how does come?

**Comment by hzsweers** [comment]
You have clearly installed something that uses it, perhaps one of the forks or another GitHub app that borrows authentication code from here?

**Comment by Damonzh** [comment]
no,i bought my phone couple days ago. This is my first install.  i am confused.

**Comment by Damonzh** [comment]
i find this  "com.github.mobile" .equals(descriptor.packageName) in AccountUtils.java . but the new ,pakageName is com.github.pockethub? if i change the pakageName to com.github.pockethub, the error disappear,but when i authenticate through the website,i always get the 404 error.

**Comment by hzsweers** [comment]
That must be a leftover from when we changed the package name, I'll fix that. Thanks for pointing that out! 

As for the 404, read the [README](https://github.com/pockethub/PocketHub#setup-environment)
