### ISSUE TITLE
Proposal to find a new app name to replace pockethub

### ISSUE THREAD

**Issue by kmav** [pockethub/PocketHub#867]
Hi,

Being an old user (and very small contributor) of github android application I have being very dissapointed to learn that this app is not anymore the official android app of Github.

I would like to kindly share with you that Pockethub, the new name of the github app is very misleading to me. It does not give the user the feeling that it is an app that relate with git. It is a hub in the pocket or something.

I would like ask you to brainstorm and find out a name that will show up and promote this great application. From my side, please let me provide the list below:

gitair, gitnode, gitorbit, gittraction (git + (at)traction), gitkernel, gitinside, gitplay, gitview, gitin, gitcrossroads, gitmobile, gitmob, giteye, gitdive, gitway, gitrandezvous, gittouch, gitall, gitjoy, gitconnect, ...

There can be thousands of alternatives. Could you please consider these or something better.

Best regards,

Konstantinos

**Comment by hzsweers** [comment]
The new name was already discussed a fair amount and chosen over other options, and we think it makes enough sense. The `Hub` postfix is just as obvious to us as a `git`, and none of the names you suggested really make any sense... :frowning:

The name is final. `Hub` is enough context, and `Pocket` is fun way of saying "mobile".

**Comment by kmav** [comment]
Hello,

Thank you for the reply.

I understand that maybe my comment arrived very late and that name is final. 

When I got for a first time some emails such as the following:
"Re: [PocketHub] Fixed build.gradle if statment wrapper (#866)"
I did not understand what was that repository/application and what was about...

Hub is maybe in context in terms of github, hub command etc. 
github has been a very successful name but could be the only one.

pocket=mobile that's OK. hub word is much less meaningful and powerful than git.

I use also other similar apps like gh4a (github for all?) that was changed octodroid. 
I believe that they should have included the word git in them. 

I am sharing to you all my thoughts and feelings about it, hoping that might be of some help. I do not want to do any harm.

Best wishes,

Konstantinos

**Comment by alorma** [comment]
Gitskarios :]

**Comment by craigjennings11** [comment]
@kmav 'Hub' is a better prefix/suffix than 'Git' for this project because the app specifically works with GitHub. Using only 'Git' could imply that it is a basic git client that can be used with any public git repo, which is not the case.

**Comment by EzraBrooks** [comment]
I would posit that it would possibly be better to have a simple, non-prefixed/suffixed name and then appending "for GitHub" to the end of the name for distribution. Although I'm not sure what GitHub's stance on that naming scheme is.

**Comment by rashmi18** [comment]
Hubbit!
