### ISSUE TITLE
app bar appearance under Lollipop

### ISSUE THREAD

**Issue by fadils** [pockethub/PocketHub#871]
Currently, it appears like this:

![screen shot 2015-08-23 at 6 23 22 am](https://cloud.githubusercontent.com/assets/6204776/9426285/342db756-4960-11e5-90a4-a8f7bed02470.png)

When it should be like this:

![screen shot 2015-08-23 at 6 28 24 am](https://cloud.githubusercontent.com/assets/6204776/9426286/4b0993a0-4960-11e5-9093-7074933551b6.png)

Tested in Api 16, 17, 18 and 19.

**Comment by Meisolsson** [comment]
It's because we use a android:layout_below here: https://github.com/pockethub/PocketHub/blob/efc2141025703b4d64d543c2a3039fba217b3a19/app/src/main/res/layout/pager_with_tabs.xml#L44-L48

Since the parent ViewGroup is not a RelativeLayout it goes to the top.

**Comment by fadils** [comment]
So, you think we should keep it this way @Meisolsson ?

**Comment by Meisolsson** [comment]
No, absolutely not. But I haven't found  way too fix it.
On Aug 24, 2015 06:01, Fadil Sutomo <notifications@github.com> wrote:So, you think we should keep it this way @Meisolsson ?
