### ISSUE TITLE
0.1.0 Release

### ISSUE THREAD

**Issue by hzsweers** [pockethub/PocketHub#872]
The following need to be done before we can get a 0.1.0 release out. @fadils @Meisolsson let me know if you think of anything else:

 - [x] Release keystore and play store account. First release will be an [open beta](http://android-developers.blogspot.com/2015/07/iterate-faster-on-google-play-with.html)
 - [x] Crash reporting tool (Bugsnag has a free open source tier)
 - [x] Remove GitHub logos from the app for legal reasons
 - [x] Log out button
 - [x] New icon
 - [x] Welcome pager that (briefly) explains this app's existence, transition this directly into the web auth
 - [x] Update copyright

**Comment by Meisolsson** [comment]
Update copyright?

**Comment by hzsweers** [comment]
Good catch, added

**Comment by larsgrefer** [comment]
Bugsnag sounds nice, but i think its not critical to be in the first release

For the question of logos and icons we may close #771 in favor of this issue

**Comment by hzsweers** [comment]
It's important to us for maintaining it. The last thing we want is to ship
an initial release and have zero information on it. It's easy to hook up as
well. Might consider tossing in google analytics as well, since it's basic
configuration gives a pretty good overview.

**Comment by fadils** [comment]
Should we fix #871 first?
Temp solution would be to remove that line and worry about the elevation for Pre-L later.
At least for 0.1.0 release, it's more acceptable that way instead of the current appearance.

Lemme know @hzsweers.
Either me or @Meisolsson can fix it real quick.

**Comment by larsgrefer** [comment]
@fadils fix it if you can, but i think this issue is acceptable for an 0.1 beta release

**Comment by skullkeeper94** [comment]
Can't wait for this! Gonna love having a GitHub app <3

**Comment by vidia** [comment]
I'm excited for this. Hopefully I can help contribute in the near future too.

**Comment by StefMa** [comment]
I think there is a little bit more to do. See https://github.com/pockethub/PocketHub/issues/880

**Comment by StefMa** [comment]
Wahh, sry. Don't see the setup on phone :-)

**Comment by larsgrefer** [comment]
@hzsweers @fadils Has anyone created a play store account and keystore so far?
If not, i can do that

**Comment by hzsweers** [comment]
Not yet, I'll handle both of those. Waiting until we're closer to a release
before we do. I'm currently in the process of starting a new job, so I've
been pretty busy and unable to really give much attention to this repo.

**Comment by larsgrefer** [comment]
If you are too busy, we can handle that, too.

**Comment by wsdjeg** [comment]
greate hope for this

**Comment by SecUpwN** [comment]
Will the [Official Github client at F-Droid](https://f-droid.org/repository/browse/?fdid=com.github.mobile) be replaced or deleted?

**Comment by hzsweers** [comment]
That's not our decision. We will not be maintaining a separate client at
F-Droid.

**Comment by SecUpwN** [comment]
>That's not our decision. We will not be maintaining a separate client at F-Droid.

So that means `PocketHub`won't be made available at F-Droid at all?

**Comment by hzsweers** [comment]
The answer [hasn't changed since the last time you asked](https://github.com/pockethub/PocketHub/issues/772#issuecomment-119809067).

**Comment by larsgrefer** [comment]
@hzsweers What exactly do you mean with "Update Copyright"?

**Comment by skullkeeper94** [comment]
Do you guys have an estimated release date?

**Comment by hzsweers** [comment]
No

**Comment by SecUpwN** [comment]
>The answer hasn't changed since the last time you asked.

@hzsweers and @fadils, I think what you might not know yet, is that you do not do **not** have to maintain *anything* when adding your app to F-Droid. When `PocketHub` gets added to the [Submission Queue](https://f-droid.org/forums/forum/submission-queue/), the GitHub source code of your project will be reviewed and the app added to F-Droid. Once you tagg and create a new release on GitHub, the version will be *automatically compiled from source* and published on F-Droid. So don't get me wrong, but I don't see *any* reason why you shouldn't add it there since it is vertually no effort at all. May I add `PocketHub` to the F-Droid Submission Queue, please?

**Comment by hzsweers** [comment]
And where are you going to get the API keys for these builds? Who is going
to be responsible if we change the build artifacts?

**Comment by SecUpwN** [comment]
>And where are you going to get the API keys for these builds?

Not sure which API keys you mean, @hzsweers. F-Droid compiles directly from the fresh source here on GitHub and signs the APK with [their own signature](https://f-droid.org/wiki/page/FAQ_-_App_Developers#What_about_signing.3F). I am sure their [FAQ](https://f-droid.org/wiki/page/FAQ_-_App_Developers) helps a bit answering questions.

>Who is going to be responsible if we change the build artifacts?

@F-Droid is an organization with FOSS at heart and I've recently had the pleasure of getting huge help from them in every aspect when we added more build flavours in [AIMSICD](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector). So should a problem exist, anyone could log in on their [F-Droid GitLab](https://gitlab.com/fdroid/fdroiddata) using their GitHub account and file an Issue. I could help, too.

**Comment by petejohanson** [comment]
GitHub's API requires there be a registered 'application' for each application that co sumes the API. Those registered apps have corresponding secret client API keys that are used for each request. For security reasons, those secret keys should not be published/shared, and as such would never be added to the PocketHub for repo. 

So F-Droid certainly can build from this repo, but it would not result in an apk that co rained a valid client secret, and would not work against the GitHub API.

See https://developer.github.com/v3/oauth/

**Comment by SecUpwN** [comment]
>So F-Droid certainly can build from this repo, but it would not result in an apk that co rained a valid client secret, and would not work against the GitHub API.

@petejohanson, thanks for the explanation. I wonder how other GitHub client apps like [ForkHub](https://github.com/jonan/ForkHub) do it?

**Comment by hzsweers** [comment]
I don't know, and I'm not going to let this thread be derailed any further. Please take no for an answer @SecUpwN. @jonan also has opted to exclusively maintain his own fork rather than help contribute to this one, so I don't expect an answer from him.

**Comment by Meisolsson** [comment]
The app has been released! https://play.google.com/store/apps/details?id=com.github.pockethub.android
