### ISSUE TITLE
IconAndViewTextManagerTest fails due to missed SDK update

### ISSUE THREAD

**Issue by froyomuffin** [pockethub/PocketHub#881]
In 0d53f750, instances of 'Event' were udpated to 'GithubEvent'. I think those in IconAndViewTextManagerTest.java were missed. It causes compilation with tests to fail due to mismatched interface:

  required: GithubEvent,StyledText,StyledText
  found: Event,\<null\>,\<null\>

I'm thinking this is probably a file that wasn't commited. If this is not the case, I can fix it and submit a pull request. :)

**Comment by StefMa** [comment]
I've created a PR for this. https://github.com/pockethub/PocketHub/pull/882

**Comment by M13Kd** [comment]
Pocket Hub is a great opportunity to add Windows LIVE client

**Comment by hzsweers** [comment]
Why would we want to add a windows LIVE client?

**Comment by larsgrefer** [comment]
This was fixed in #882. I think we can close this now.

**Comment by froyomuffin** [comment]
Just tried it. Works good :D
