### ISSUE TITLE
Long Click in news page Crash

### ISSUE THREAD

**Issue by ChunxiaZhang** [pockethub/PocketHub#892]
Login GitHub, go to news page of my account directly;
Long click one of news, popup up a menu, click news' owner's repo, then turn to this owner's news page;
Then long click one of news, popup up the menu again, then click this owner's repo again;
Long click one of news, then Crash.

I found in ConvertUtils.java, split the Repo by "/" in to String array, but doesn't verify the array's length.  Follow these steps, execute String[] ref = repo.name.split("/"), the ref has only one item, then repo.name = ref[1];  try to access the second item.

**Comment by Meisolsson** [comment]
This has been fixed (#920)
