### ISSUE TITLE
Logout removes all accounts on the phone...

### ISSUE THREAD

**Issue by Meisolsson** [pockethub/PocketHub#893]
We are currently removing all the account on the phone when logging out. At least for my phone all of my email accounts are removed when logging out.

Device: Nexus 5
Android version: 5.1.1

    Account[] allAccounts = AccountManager.get(this).getAccounts();
        for (Account account : allAccounts) {
            AccountManager.get(this).removeAccount(account, null, null);
        }

Above we get all the accounts on the device instead of getting them by type

**Comment by larsgrefer** [comment]
I think we should distinguish between switching accounts, and removing them.

Take a look at the gmail app. There you can easily switch between different mail accounts in the Navigation drawer

**Comment by StefMa** [comment]
See the PR here: https://github.com/pockethub/PocketHub/pull/898

**Comment by larsgrefer** [comment]
#898 is merged, so we should close this issue
