### ISSUE TITLE
Using gradle to publish APK's to google play

### ISSUE THREAD

**Issue by larsgrefer** [pockethub/PocketHub#902]
https://github.com/Triple-T/gradle-play-publisher

This is a gradle plugin which can upload apks and more to google play, we can combine this with travis in order to achieve continuous delivery.

What do you think about that? @fadils @Meisolsson @hzsweers

**Comment by hzsweers** [comment]
I would be ok with that, but not every push to master. Would much rather
prefer we use that for an alpha channel with nightly builds.

**Comment by larsgrefer** [comment]
production builds have to be choosen by hand of course, but for beta and alpha phases, we can set up travis in order to push the apk's

**Comment by hzsweers** [comment]
The play store has a daily limit for the API, and it's much less than pushes to master would allow. Nightlies would be fine

**Comment by larsgrefer** [comment]
Can travis be configured in order to run nightly builds?

Another idea is a deploy-script like: *Only push to google play if you haven't already done it earlier this day*

**Comment by hzsweers** [comment]
Not sure if Travis could or shouls, but something like heroku could. The
second part is a little too hand wavy for me, can you be more specific as
to how that would work?

**Comment by larsgrefer** [comment]
The deploy-script on travis would have to check when the last deploy was made. Then the script could determine if it`s long enough ago. At the moment I have two ideas how the script could get the last-deploy timestamp:
- Asking the play store (not sure if the api supports that)
- Store the timestamp to [cache](https://docs.travis-ci.com/user/caching)

**Comment by spudowiar** [comment]
What about asking Travis CI or GitHub? One of those will allow you to get the last successful build, then you just check the timestamp.

**Comment by hzsweers** [comment]
@spudowiar read the thread, we discussed Travis. GitHub doesn't do builds for you.

**Comment by spudowiar** [comment]
@hzsweers I'm referring to the comment by @larsgrefer. GitHub doesn't do the builds but it stores which commit was the last successful Travis build.
