### ISSUE TITLE
Explain who is the pockethub organization

### ISSUE THREAD

**Issue by larsgrefer** [pockethub/PocketHub#914]
You should add a few sentences to the README.md in order to explain who is the pockethub organization.

I know that the organization was created by github in order to move the repository out of the github-organization, but i don't know who is in the new pockethub-organization and why.
Additionally it'd be nice to know if someone is *the boss*.

**Comment by hzsweers** [comment]
Why does there need to be a boss? We're a team of 3 people right now just trying to get this organized and back out there. The README explains the rest already, and I've added a line explaining `PocketHub`.
