### ISSUE TITLE
404 error when initial login is attempted

### ISSUE THREAD

**Issue by abcminiuser** [pockethub/PocketHub#916]
I've just compiled and installed ee3e4a38ee2acc6addd775ad52d577751593c986 as a fresh new user (uninstalled my very old version from when it was an official GitHub app). After attempting to log in from the start up screen, I enter my GitHub details and then get stuck on a GitHub 404 page. I can't proceed any further than this.

It looks to be server-side, but perhaps the app is requesting a page or API endpoint that no longer exists.

Tested on a Nexus 4, with 5.1.1.

**Comment by larsgrefer** [comment]
Have you done this?:
https://github.com/pockethub/PocketHub#setup-environment

**Comment by abcminiuser** [comment]
I...have brought great shame to my family. I missed that - I'll give it a go this evening. Would it make sense to introduce a compile error if the configuration values are not correctly set?

**Comment by abcminiuser** [comment]
..and of course, it works. Sorry for the false alarm.

**Comment by larsgrefer** [comment]
A compiler error would break all unit tests on travis, but i'm going to modify the build script to show a warning
