### ISSUE TITLE
Toolbar title should reflect current selected section.

### ISSUE THREAD

**Issue by joaocsousa** [pockethub/PocketHub#925]
I guess this a bit open to discussion and individual preferences, but I wanted to bring this up anyway.

Shouldn't the toolbar title reflect the current selected section from the drawer menu? Currently, the main activity's title is always the app name, but for someone like me who is starting to use this app it can be quite confusing sometimes to know where I am within the app.

<img width="961" alt="presentation1" src="https://cloud.githubusercontent.com/assets/1117022/10417199/69f9d3a6-702a-11e5-88de-c5744e165c50.png">

**Comment by StefMa** [comment]
Yeah, great idea. I will make a PR...

**Comment by larsgrefer** [comment]
:+1: we should change that

**Comment by StefMa** [comment]
"Home" will be stay on PocketHub? Or also replaced with Home?

**Comment by larsgrefer** [comment]
i think Home should stay on the application name

**Comment by Meisolsson** [comment]
This has been implemented now (#926)
