### ISSUE TITLE
Replace octocat loading icon with standard indeterminate progressbar

### ISSUE THREAD

**Issue by larsgrefer** [pockethub/PocketHub#931]
At the moment most of the lists have 2 possible loading animations:
1. the octocat with the spinning circle around
2. the loading spinner supplied by `SwipeRefreshLayout`

I think there should be only one loading animation.

In #872 its said, that the github logo should be removed from the app, so I`d prefer using option 2.
What are your opinions about that?

**Comment by hzsweers** [comment]
They have different use cases. One is for scrollable content views, the other is for loading dialogs. They should be separate, albeit the octocat should be replaced with a standard indeterminate progress indicator.

**Comment by larsgrefer** [comment]
@hzsweers I agree with you to use a a standard indeterminate progress indicator, but thats not the point I meant.

Im only talking about the scrollable content views. Those use the custom spinner (with the logo inside) for inital loading, but the SwipeRefreshLayout-spinner for subsquent refreshes.
And in some cases you can achieve to see both spinners at the same time.

In my opinion the SwipeRefreshLayout spinner should be used for all loading-operations of the specific list: The initial loading AND refreshes

**Comment by hzsweers** [comment]
Ah, this should be two separate issues then.
