### ISSUE TITLE
Background image of the NavigationDrawer header

### ISSUE THREAD

**Issue by larsgrefer** [pockethub/PocketHub#932]
At the moment the background of the navigation drawer header contains an image with an octocat.

accroding to #872 the github icon shoud be removed from the app, so this background has to be exchanged as well, right?

My suggestion is to just use `?attr/colorPrimaryDark` until someone has a better idea.

What are your opinions?

**Comment by ahmedre** [comment]
in addition, on a Nexus 6, the background doesn't cover the entire drawer horizontally...

![2015-11-01 04 24 17](https://cloud.githubusercontent.com/assets/47771/10867271/dcefb70e-8015-11e5-8100-7a190c9e5d62.png)

**Comment by fadils** [comment]
close via #954
