### ISSUE TITLE
Branch commit list option: --first-parent

### ISSUE THREAD

**Issue by ferranpujolcamins** [pockethub/PocketHub#940]
Hi! I would like to add the option the option to "hide" the commits introduced by a merge, as in "git log --first-parent". I'm new both to the project and android development, so I'm a little bit lost. Could you help me with:

1) Where is the code that decides which commits are shown (and which order) in the commit list?

2) What would be the preferred UI to toggle this option?

**Comment by larsgrefer** [comment]
1) Im afraid the code you are looking for is in githubs rest-api. The app just calls the rest-api, coverts the json to java objects and displays them in a fragment.

2) maybe a checkbox or a toggle?
