### ISSUE TITLE
can you please provide supoort for maven?

### ISSUE THREAD

**Issue by wsdjeg** [pockethub/PocketHub#943]
i am using maven to vreate my android app,many time the code ontained in the public pc,we need to use command to create app,so can you add maven support?
https://github.com/wsdjeg/maven-android-sdk-deployer
this project help me add the sdk into ~/.m2/

**Comment by hzsweers** [comment]
I don't understand what you're asking. This repo is not an SDK, nor are we going to support building in maven and gradle simultaneously.

**Comment by wsdjeg** [comment]
i know ,this repo the android app for github,i just want to use `mvn package android:deploy` install it into my phone
maven-android-sdk-deployer is a project for android-sdk,not for this

**Comment by hzsweers** [comment]
fork it and do it yourself? We don't use maven

**Comment by wsdjeg** [comment]
with the help of https://github.com/wsdjeg/maven-android-sdk-deployer
i can use this dependency
```xml
<dependency>
  <groupId>android</groupId>
  <artifactId>android</artifactId>
  <version>x.y.z</version>
  <scope>provided</scope>
</dependency>
```

**Comment by wsdjeg** [comment]
i have forked it,and now i am just try to do it

**Comment by hzsweers** [comment]
I'm not sure what you need from us still

**Comment by wsdjeg** [comment]
i just don't know how to add dependency of githun-sdk,i have search it in maven center repo,but there is no dependency for github-sdk

**Comment by hzsweers** [comment]
We use this SDK now: https://github.com/gitskarios/GithubAndroidSdk

**Comment by wsdjeg** [comment]
i also have forked ,and try to add pom.xml,here is my fork,https://github.com/wsdjeg/GithubAndroidSdk/blob/master/pom.xml
should i  change the `<packaging>apk</packaging>`to`<packaging>jar</packaging>`

**Comment by wsdjeg** [comment]
great i think i have got it
![2015-10-25 09-37-36](https://cloud.githubusercontent.com/assets/13142418/10713626/146cedf6-7afc-11e5-906a-708f760e8e77.png)

**Comment by larsgrefer** [comment]
@wsdjeg Instead of `mvn package android:deploy` you can use `./gradlew app:installDebug` to install this app on your phone

The `github-sdk` can be found in the jcenter maven repository as `com.github.alorma:github-sdk:1.2.0`
(http://jcenter.bintray.com/com/github/alorma/github-sdk/)

For more information about why this app is build with gradle and not with maven, have a look at #602

**Comment by wsdjeg** [comment]
@larsgrefer thank you for your reply

i will have a try with gradle

**Comment by wsdjeg** [comment]
i have download the gradle from the it's web,and add this to my zshrc,how could i build this app
```
export GRADLE_HOME="$HOME/others/gradle-2.8"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$GRADLE_HOME/bin:$PATH"
```

**Comment by wsdjeg** [comment]
it does not work for me 
stop here for an hour
> Configuring > 3/3 projects > Resolving dependencies ':app:_debugCompile'

**Comment by larsgrefer** [comment]
@wsdjeg you don't have to download gradle by hand or set the `GRADLE_HOME` variable, just use the `gradlew` script provided in this repository: `./gradlew app:installDebug`

**Comment by wsdjeg** [comment]
i know ,i just use this command `./gradlew app:installDebug`,but it stop here for a long time
