### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by fringerdarlinger** [pockethub/PocketHub#948]
It would be great if you submitted this to F-Droid. We are missing a good Github client

**Comment by larsgrefer** [comment]
@fringerdarlinger Have a look at #872

**Comment by fringerdarlinger** [comment]
Ah! Thanks. I'll keep a watch on you then.

**Comment by IzzySoft** [comment]
Seeing the reasons (from the linked issue), what about releasing the `.apk` here at Github – especially for those without Playstore access? Speaking of which, the [releases page](https://github.com/pockethub/PocketHub/releases) looks like the last release was made back in 2014 :)

PS: With the `.apk` available from the `releases/` page, I could (automatically) pick each new release and serve it with [my F-Droid compatible repo](https://android.izzysoft.de/repo) to solve the initial request :)

**Comment by Meisolsson** [comment]
For now (We might change our minds in the future) will not be uploading to F-Droid or the GitHub.

**Comment by IzzySoft** [comment]
OK, I see. My offer stands, in case you change your mind just ping me. I'm subscribed to this issue, so adding a new comment here would bring me a notification then. Thanks!
