### ISSUE TITLE
Changing username results in 404 errors

### ISSUE THREAD

**Issue by SamThompson** [pockethub/PocketHub#959]
I recently changed my username, and I get 404 errors when I try to load anything.

I haven't looked at the github api, but there should be some endpoint to get the username of a given oauth token.

I would just log out and back in, but I can't seem to find where to log out (not sure if this is related).

**Comment by fadils** [comment]
You should build against our latest `master`. Meanwhile, we are trying to update the PlayStore version, as soon as possible.

**Comment by hzsweers** [comment]
Sam isn't using the play store version I don't think

**Comment by fadils** [comment]
Ah, my bad..
Are you doing similar with #819 ?

**Comment by SamThompson** [comment]
Yep, that's it. For some reason that issue didn't come up when I searched earlier. Feel free to mark this as a duplicate

**Comment by hzsweers** [comment]
Dupe of #819
