### ISSUE TITLE
Blank page when clicking on any issue thread

### ISSUE THREAD

**Issue by cdysthe** [pockethub/PocketHub#962]
When I click on an issue thread I get a blank window. Title bar on top and then nothing. I'm running the app on an Oppo Find 7 with Android 5.1. Am I missing something obvious?

**Comment by Meisolsson** [comment]
Are you running the play store version? That verison is no longer supported.

**Comment by hzsweers** [comment]
I'm closing this, we no longer accept issues that don't specify this per our CONTRIBUTING.MD guidelines.

**Comment by cdysthe** [comment]
I have no idea what CONTRIBUTING.MD is. I'm just a user. Well, a previous user 😉

**Comment by larsgrefer** [comment]
@cdysthe When you create an Issue here, GitHub shows you this message: 
> Please review the [guidelines for contributing](https://github.com/pockethub/PocketHub/blob/master/CONTRIBUTING.md) to this repository.

The message contains a link to file named CONTRIBUTING.md

**Comment by cdysthe** [comment]
Okay, so I read that and have no idea what I did wrong. Anyway, found another client that works but thank you for letting me know 😀

**Comment by CrazyBay** [comment]
Me too 🤓🤓🤓


发自 网易邮箱大师
在2015年12月02日 19:49，Christian Dysthe 写道:

I have no idea what CONTRIBUTING.MD is. I'm just a user. Well, a previous user 😉
