### ISSUE TITLE
Readme in RepositoryView

### ISSUE THREAD

**Issue by StefMa** [pockethub/PocketHub#966]
Hey together,

what is the first thing that "jump in your eye" when you visit a GitHub-Project? Right, the README-File.
Would it be great if you, inside the app, see the README too as a eye catcher?
I think so.
For that I've started here https://github.com/stefma/PocketHub/tree/newRepositoryView a new look for the repository view. It isn't actually because MARKDOWN in Android is... argh! 

But. What is my goal.
I want to add a new Tab in TabLayout in the RepositoryView. It would be the first Tab with "Overview". I think it is better than "Readme". But it's just naming convention. What ever.
In this you can see the whole README in Markdown. If exist. Otherwise the Tab isn't available.

My current problems:
* As mentioned above, MARKDOWN in Android is very ugly. All libs (like our current) reform the Markdown to HTML and display it to a WebView. The problem, we can't set a WebView in the first tab because it catch the "scrolling" inside the ViewPager. Yes we can remove the catching touch and force a scroll via ViewPager but the HTML-Generatoed code "overlaps" the WebView content. So you can't see the whole text...

* I've actually never worked with the GitHub-Api. But I need it "BEFORE" we open the Repo-View because to setup the Tabs. We need to find (or not) the README-File in the root-tree and display it. That's very bad. Because the used needs to wait for a online-response.. :(

Ok, thats all for the first time :)

Any suggestions for that? Is it a good think, a bad? What do you think?

**Comment by hzsweers** [comment]
This is already planned via #860, can you add your thoughts to that instead?
