### ISSUE TITLE
Commenting on commits crashes

### ISSUE THREAD

**Issue by hzsweers** [pockethub/PocketHub#975]
https://github.com/gitskarios/GithubAndroidSdk/issues/42

**Comment by Meisolsson** [comment]
Well then we need a custom build or update too use the updated SDK. The new SDK switches all of the methods to used Observable so there's some work to be done

**Comment by hzsweers** [comment]
Started on this in https://github.com/pockethub/PocketHub/tree/z/sdk_update

**Comment by hzsweers** [comment]
Should be fixed in #976
