### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by vyasgiridhar** [pockethub/PocketHub#978]
Logging in directly goes into a 404 error

**Comment by Meisolsson** [comment]
Have you followed "Setup Environment" (https://github.com/pockethub/PocketHub#setup-environment)?

**Comment by sorab2142** [comment]
I can confirm the same thing happened to me as well.
Even after following Setup Environment, could someone clarify those steps further?

**Comment by hzsweers** [comment]
Closed due, assumed user error.
