### ISSUE TITLE
Add some space between title and avatar .

### ISSUE THREAD

**Issue by altaf933** [pockethub/PocketHub#983]
Kindly find attache screenshot of GistFileFragment.java screen and it's small ui changes . These screenshot has taken from the OS version is: 4.2.1
![screenshot_2016-02-26-12-33-01](https://cloud.githubusercontent.com/assets/5979711/13347748/b5398d20-dc95-11e5-8cbb-9122fb0827fe.png)

**Comment by kubaspatny** [comment]
I had a look at the layout, I would like to optimize it a bit as well as increase the space between the avatar and labels.

Is that OK?

**Comment by hzsweers** [comment]
PRs welcome

**Comment by andrewlord1990** [comment]
@hzsweers: Looks like this issue can be closed.
