### ISSUE TITLE
App not present in recents when opened from a hyperlink 

### ISSUE THREAD

**Issue by aandis** [pockethub/PocketHub#993]
If the app opens from an intercepted hyperlink, it doesn't show up in `Recents`.

**Comment by aandis** [comment]
![ezgif com-resize](https://cloud.githubusercontent.com/assets/4983347/13693906/2328b636-e776-11e5-8af4-a1489c5f9382.gif)

**Comment by hzsweers** [comment]
This is normal behavior, it doesn't synthesize a backstack and some tasks behave like this in recents on android

**Comment by aandis** [comment]
Is there any particular reason [this](https://github.com/pockethub/PocketHub/blob/master/app/src/main/AndroidManifest.xml#L257) was done? If I open the app from an outside link, isn't it more natural to treat it as if it was a normal application flow(like most other apps) and give users the ability to switch apps as usual?

**Comment by hzsweers** [comment]
I, and most users I think, would disagree. That's fairly standard for handling deep links. Your user was navigated to your app from somewhere else, likely just to glance at something or do a quick response.

**Comment by aandis** [comment]
Besides not having the ability to switch apps, what excluding this from `Recents` does is that, the activity doesn't really close once you click on `Recents`, it just doesn't show up there. So say, if you pressed `back` (from the top left icon) and *then* clicked on `Recents` it would look like the app was killed but if you go back again to the app from a deep link, it would open back the same activity which was never killed, and will not open what the deep link was meant to open.

**Comment by aandis** [comment]
gif incoming..

**Comment by aandis** [comment]
![ezgif com-resize 1](https://cloud.githubusercontent.com/assets/4983347/13694684/d6af655e-e77d-11e5-8942-e1c697557ec9.gif)

**Comment by aandis** [comment]
>  it doesn't synthesize a backstack

I am not saying we should create a backstack in this case. That's not really necessary. All I am saying is, don't exclude this from the `Recents`. [Recents](http://developer.android.com/guide/components/recents.html) exists to list out recently accessed activities and tasks, so it's only natural this shows up there. Having this up there will also avoid bug mentioned in https://github.com/pockethub/PocketHub/issues/993#issuecomment-195201759 because user has the ability to kill the activity.

**Comment by hzsweers** [comment]
I can't tell what's wrong with that gif, nor did I understand what you were describing in your hypothetical situation. Pressing the home button does bring you farther back into the app, that seems like normal behavior to me. Pressing the navigation back button would go back to your email.

This is also important for cases where you don't actually need to handle a deeplink with UI, such as our callback for oauth login. I'm sorry but you'll have to accept this for now, I can look at it more when I have time.

**Comment by aandis** [comment]
> I can look at it more when I have time.

I am willing to fix this if you'd be willing to accept the fix. :) But alright, I have explained why this is necessary. Think about it when you can. :)

**Comment by hzsweers** [comment]
I need to look at it and see if it still makes sense behaviorally. The fix is just a one-liner, not much work for me :P

**Comment by aandis** [comment]
> The fix is just a one-liner

I thought so too at first. ;) 
But the way it's written now, what would happen is, you can end up with multiple activities from the same app in `Recents` once you remove the [condition](https://github.com/pockethub/PocketHub/blob/master/app/src/main/AndroidManifest.xml#L257). Something like this 
![rsz_screenshot_2016-03-11-12-36-42](https://cloud.githubusercontent.com/assets/4983347/13695591/47cf9dbe-e786-11e5-879b-c965cc036147.png)

which is also not very good ux :). So we'd need to fix that as well.
