### ISSUE TITLE
Snapshot builds?

### ISSUE THREAD

**Issue by rmenessec** [pockethub/PocketHub#996]
I'm very interested in testing / using PocketHub, but I'm not an Android developer by any stretch of the imagination. It would be awesome if someone could provide periodic snapshot builds from master.

Thanks!

**Comment by hzsweers** [comment]
Just clone it and build it, we don't have plans around setting up snapshots right now.

**Comment by ahangchen** [comment]
@rmenessec I fork this repository and build an apk for it. If you don't mind, you can try it.[Download](https://github.com/ahangchen/PocketHub/blob/master/pockethub-debug.apk?raw=true)

**Comment by rmenessec** [comment]
@ahangchen - Many thanks! I do not have access to the necessary build tools atm.
